--USE master
--DROP DATABASE DEAN4
--CREATE DATABASE DEAN4
--USE DEAN4

select * from [dbo].[UserSessions]
USE master
DROP DATABASE DEAN5

--CREATE DATABASE DEAN
--ON PRIMARY
--(
--	NAME = MATKINH_PRIMARY,
--	FILENAME = 'E:\LuuDuLieuSinhVien\2001222777_THAIDANGPHUONGNAM\Hệ_quản_trị_cơ_sở_dl\mk_primary.mdf',
--	SIZE = 50 MB,
--	MAXSIZE = 100 MB,
--	FILEGROWTH = 10 MB
--),

--(
--	NAME = MATKINH_SECOND,
--	FILENAME = 'E:\LuuDuLieuSinhVien\2001222777_THAIDANGPHUONGNAM\Hệ_quản_trị_cơ_sở_dl\mk_second.ndf',
--	SIZE = 30 MB,
--	MAXSIZE = 50 MB,
--	FILEGROWTH = 15%
--)

--LOG ON 
--(
--	NAME = MATKINH_Log,
--	FILENAME = 'E:\LuuDuLieuSinhVien\2001222777_THAIDANGPHUONGNAM\Hệ_quản_trị_cơ_sở_dl\mk_log.ldf',
--	SIZE = 40 MB,
--	MAXSIZE = 80 MB,
--	FILEGROWTH = 20%
--) 

CREATE DATABASE DEAN5
--ON PRIMARY
--(
--	NAME = MATKINH_PRIMARY,
--	FILENAME = 'C:\Users\Lenovo\Downloads\HQTCSDL TUAN04\mk_primary.mdf',
--	SIZE = 50 MB,
--	MAXSIZE = 100 MB,
--	FILEGROWTH = 10 MB
--),

--(
--	NAME = MATKINH_SECOND,
--	FILENAME = 'C:\Users\Lenovo\Downloads\HQTCSDL TUAN04\mk_second.ndf',
--	SIZE = 30 MB,
--	MAXSIZE = 50 MB,
--	FILEGROWTH = 15%
--)

--LOG ON 
--(
--	NAME = MATKINH_Log,
--	FILENAME = 'C:\Users\Lenovo\Downloads\HQTCSDL TUAN04\mk_log.ldf',
--	SIZE = 40 MB,
--	MAXSIZE = 80 MB,
--	FILEGROWTH = 20%
--) 

GO 

USE DEAN5

GO
SP_SPACEUSED


/*=======================================TAOBANG==================================*/
CREATE TABLE KHACHHANG
(
	MAKH INT IDENTITY(1,1) NOT NULL,
	TENKH NVARCHAR(25),
	DIACHI NVARCHAR(25),
	SODT CHAR(12),
	CONSTRAINT PK_KHACHHANG PRIMARY KEY(MAKH)
)
SELECT * FROM KHACHHANG

CREATE TABLE NHANVIEN
(
	MANV INT IDENTITY(1,1) NOT NULL,
	TENNV NVARCHAR(50),
	CHUCVU NVARCHAR(50),
	MANV_QUANLY INT, -- Đây là khóa ngoại tham chiếu đến chính bảng NHANVIEN
	CONSTRAINT PK_NHANVIEN PRIMARY KEY(MANV),
	CONSTRAINT FK_NHANVIEN_QUANLY FOREIGN KEY(MANV_QUANLY) REFERENCES NHANVIEN(MANV)
)
SELECT * FROM NHANVIEN

CREATE TABLE THONGTINNHANVIEN
(
	MANV INT NOT NULL,
	NGAYSINH DATE,
	GIOITINH NVARCHAR(10),
	CMND CHAR(12) UNIQUE, -- Số CMND/CCCD là duy nhất
	EMAIL NVARCHAR(50) UNIQUE, -- Email là duy nhất
	CONSTRAINT PK_THONGTINNHANVIEN PRIMARY KEY(MANV),
	CONSTRAINT FK_THONGTINNHANVIEN_NHANVIEN FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV) 
)
SELECT * FROM THONGTINNHANVIEN


CREATE TABLE HOADON
(
	MAHD CHAR(100) NOT NULL,
	NGAYLAP DATE,
	TRANGTHAI NVARCHAR(30),
	MAKH INT NULL,
	MANV INT,
	CONSTRAINT PK_HOADON PRIMARY KEY(MAHD),
	CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH),
	CONSTRAINT FK_HOADON_NHANVIEN FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV),
)
SELECT * FROM HOADON
-- Thay đổi khóa ngoại MAKH trong bảng HOADON để cho phép giá trị NULL
ALTER TABLE HOADON
DROP CONSTRAINT FK_HOADON_KHACHHANG;

ALTER TABLE HOADON
ALTER COLUMN MAKH INT NULL;

ALTER TABLE HOADON
ADD CONSTRAINT FK_HOADON_KHACHHANG
FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH);

DROP TABLE CHITIETHOADON
DROP TABLE HOADON
DROP TABLE KHUYENMAI
DROP TABLE CHITIETKHUYENMAI


CREATE TABLE KHUYENMAI
(
    MAKM INT IDENTITY(1,1) NOT NULL, -- Mã khuyến mãi
    TENKM NVARCHAR(100) NOT NULL UNIQUE, -- Tên mã khuyến mãi
	DIEUKIEN_APDUNG FLOAT NOT NULL, -- Điều kiện áp dụng về tổng tiền
    GIAMGIA FLOAT NOT NULL,   -- Phần trăm giảm giá
    MOTA NVARCHAR(255), -- Mô tả mã khuyến mãi (tuỳ chọn)
    CONSTRAINT PK_KHUYENMAI PRIMARY KEY(MAKM)
);
SELECT * FROM KHUYENMAI


CREATE TABLE CHITIETKHUYENMAI
(
    MAHD CHAR(100) NOT NULL,        -- Mã hóa đơn
    MAKM INT NOT NULL,        -- Mã khuyến mãi
    MAHG INT NULL,            -- Mã hàng hóa (có thể NULL nếu áp dụng cho toàn bộ hóa đơn)
    CONSTRAINT PK_CHITIETKHUYENMAI PRIMARY KEY (MAHD, MAKM), -- Khóa chính kết hợp
    CONSTRAINT FK_CHITIETKHUYENMAI_HOADON FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
    CONSTRAINT FK_CHITIETKHUYENMAI_KHUYENMAI FOREIGN KEY (MAKM) REFERENCES KHUYENMAI(MAKM),
    CONSTRAINT FK_CHITIETKHUYENMAI_HANGHOA FOREIGN KEY (MAHG) REFERENCES HANGHOA(MAHG)
);
SELECT * FROM CHITIETKHUYENMAI


CREATE TABLE LOAIHANG
(
	MALOAI INT IDENTITY(1,1) NOT NULL,
	TENLOAI NVARCHAR(50) UNIQUE,--Tên loại hàng là duy nhất
	CONSTRAINT PK_LOAIHANG PRIMARY KEY(MALOAI)
)
SELECT * FROM LOAIHANG

CREATE TABLE HANGHOA
(
	MAHG INT IDENTITY(1,1) NOT NULL,
	TENHANG NVARCHAR(25),
	DVT NVARCHAR(30) DEFAULT 'Chưa xác định',--Mặc định là 'chưa xác định' nếu để trống
	MALOAI INT,
	CONSTRAINT PK_HANGHOA PRIMARY KEY(MAHG),
	CONSTRAINT FK_HANGHOA_LOAIHANG FOREIGN KEY(MALOAI) REFERENCES LOAIHANG(MALOAI)
)
ALTER TABLE HANGHOA
ADD DONGIA FLOAT

ALTER TABLE HANGHOA
ADD CONSTRAINT DF_HANGHOA_DONGIA DEFAULT 0 FOR DONGIA;

ALTER TABLE HANGHOA
ADD HINH NVARCHAR(100)


SELECT * FROM HANGHOA

CREATE TABLE CHITIETHOADON
(
	MAHD CHAR(100) NOT NULL,
	MAHG INT NOT NULL,
	SOLUONG INT DEFAULT 0,--Giá trị mặc định là 0 nếu để trống
	GIABAN FLOAT DEFAULT 0,--Giá trị mặc định là 0 nếu để trống
	CONSTRAINT PK_CHITIETHOADON PRIMARY KEY(MAHD, MAHG),
	CONSTRAINT FK_CHITIETHOADON_HOADON FOREIGN KEY(MAHD) REFERENCES HOADON(MAHD),
	CONSTRAINT FK_CHITIETHOADON_HANGHOA FOREIGN KEY(MAHG) REFERENCES HANGHOA(MAHG),
	CONSTRAINT CHK_CHITIETHOADON_SOLUONG CHECK(SOLUONG>=0),--Số lượng không được là số âm
	CONSTRAINT CHK_CHITIETHOADON_GIABAN CHECK(GIABAN>=0)--Giá bán không được là số âm
)
SELECT * FROM CHITIETHOADON

CREATE TABLE NHACC
(
	MANCC INT IDENTITY(1,1) NOT NULL,
	TENNCC NVARCHAR(15) NOT NULL UNIQUE,--Tên nhà cung cấp là duy nhất
	DIACHI NVARCHAR(25), 
	SODT CHAR(12),
	CONSTRAINT PK_NHACC PRIMARY KEY(MANCC),
)
SELECT * FROM NHACC

CREATE TABLE PHIEUNHAP
(
	MAPN CHAR(100) NOT NULL,
	NGAYNHAP DATE,
	MANCC INT,
	MANV INT,
	CONSTRAINT PK_PHIEUNHAP PRIMARY KEY(MAPN),
	CONSTRAINT FK_PHIEUNHAP_NHACC FOREIGN KEY(MANCC) REFERENCES NHACC(MANCC),
	CONSTRAINT FK_PHIEUNHAP_NHANVIEN FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)
)
SELECT * FROM PHIEUNHAP

CREATE TABLE CHITIETPN
(
	MAPN CHAR(100) NOT NULL,
	MAHG INT NOT NULL,
	SOLUONG INT DEFAULT 0,--Giá trị mặc định là 0 nếu để trống
	GIABAN FLOAT DEFAULT 0,--Giá trị mặc định là 0 nếu để trống
	CONSTRAINT PK_CHITIETPN PRIMARY KEY(MAPN, MAHG),
	CONSTRAINT FK_CHITIETPN_PHIEUNHAP FOREIGN KEY(MAPN) REFERENCES PHIEUNHAP(MAPN),
	CONSTRAINT FK_CHITIETPN_HANGHOA FOREIGN KEY(MAHG) REFERENCES HANGHOA(MAHG),
	CONSTRAINT CHK_CHITIETPN_SOLUONG CHECK(SOLUONG>=0),--Số lượng không được là số âm
	CONSTRAINT CHK_CHITIETPN_GIABAN CHECK(GIABAN>=0)--Giá bán không được là số âm
)
SELECT * FROM CHITIETPN

CREATE TABLE LICHCA (
    MACA INT IDENTITY(1,1) NOT NULL,       -- Mã ca làm việc (khóa chính)
    TENCACAO NVARCHAR(50),     -- Tên ca làm việc (ví dụ: "Ca sáng", "Ca chiều")
    THOIGIANBATDAU TIME,       -- Thời gian bắt đầu ca
    THOIGIANKETTHUC TIME       -- Thời gian kết thúc ca
	CONSTRAINT PK_LICHCA PRIMARY KEY(MACA)
);

CREATE TABLE LICHTRUC (
    MANV INT,                  -- Mã nhân viên
    MACA INT,                  -- Mã ca làm việc (liên kết với bảng LichCa)
    NGAYTRUC DATE,            -- Ngày trực của nhân viên
    PRIMARY KEY (MANV, MACA, NGAYTRUC),  -- Khóa chính kết hợp để đảm bảo mỗi nhân viên không bị phân trùng ca vào một ngày
    CONSTRAINT FK_LICHTRUC_LICHCA FOREIGN KEY (MACA) REFERENCES LichCa(MACA),  -- Khóa ngoại liên kết tới LichCa
    CONSTRAINT FK_LICHTRUC_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)  -- Khóa ngoại liên kết tới bảng NHANVIEN
);

CREATE TABLE CHAMCONG
(
    MANV INT,                          -- Mã nhân viên
    MACA INT,                          -- Mã ca làm việc (tham chiếu từ LichTruc)
    NGAYLAM DATE,                      -- Ngày làm việc
    THOIGIANVAO TIME,                  -- Thời gian vào làm
    THOIGIANRA TIME,                   -- Thời gian ra về
	GHICHU NVARCHAR(100)
    CONSTRAINT PK_CHAMCONG PRIMARY KEY (MANV, NGAYLAM, MACA), -- Khóa chính kết hợp
    CONSTRAINT FK_CHAMCONG_LICHTRUC FOREIGN KEY (MANV, MACA, NGAYLAM) REFERENCES LICHTRUC(MANV, MACA, NGAYTRUC) -- Liên kết với LichTruc
);
SELECT * FROM CHAMCONG

/*=======================================NHẬP DỮ LIỆU VÀO DATABASE==================================*/
-- Bảng KHACHHANG (Khách hàng)
INSERT INTO KHACHHANG(TENKH, DIACHI, SODT) VALUES (N'Nguyễn Văn A', N'Hà Nội', '0123456789');
INSERT INTO KHACHHANG(TENKH, DIACHI, SODT) VALUES (N'Phạm Thị B', N'Hồ Chí Minh', '0987654321');
INSERT INTO KHACHHANG(TENKH, DIACHI, SODT) VALUES (N'Lê Hoàng C', N'Đà Nẵng', '0912345678');
INSERT INTO KHACHHANG(TENKH, DIACHI, SODT) VALUES (N'Ngô Thị D', N'Bình Dương', '0943214567');
INSERT INTO KHACHHANG(TENKH, DIACHI, SODT) VALUES (N'Vũ Văn E', N'Cần Thơ', '0967543212');
INSERT INTO KHACHHANG(TENKH, DIACHI, SODT) VALUES (N'Hoàng Thị F', N'Hải Phòng', '0931234567');
INSERT INTO KHACHHANG(TENKH, DIACHI, SODT) VALUES (N'Trần Văn G', N'Quảng Ninh', '0975123456');
INSERT INTO KHACHHANG(TENKH, DIACHI, SODT) VALUES (N'Bùi Thị H', N'Bắc Ninh', '0923456712');
INSERT INTO KHACHHANG(TENKH, DIACHI, SODT) VALUES (N'Đỗ Văn I', N'Vũng Tàu', '0991234567');
INSERT INTO KHACHHANG(TENKH, DIACHI, SODT) VALUES (N'Đinh Thị K', N'Hà Tĩnh', '0954321678');
SELECT * FROM KHACHHANG

-- Bảng NHANVIEN (Nhân viên)
INSERT INTO NHANVIEN(TENNV, CHUCVU, MANV_QUANLY) VALUES (N'Trần Văn A', N'Quản lý', NULL);
INSERT INTO NHANVIEN(TENNV, CHUCVU, MANV_QUANLY) VALUES (N'Nguyễn Thị B', N'Nhân viên', 1);
INSERT INTO NHANVIEN(TENNV, CHUCVU, MANV_QUANLY) VALUES (N'Lê Hoàng C', N'Nhân viên', 1);
INSERT INTO NHANVIEN(TENNV, CHUCVU, MANV_QUANLY) VALUES (N'Phạm Văn D', N'Nhân viên', 1);
INSERT INTO NHANVIEN(TENNV, CHUCVU, MANV_QUANLY) VALUES (N'Vũ Thị F', N'Nhân viên', 1);
INSERT INTO NHANVIEN(TENNV, CHUCVU, MANV_QUANLY) VALUES (N'Bùi Văn G', N'Nhân viên', 1);
INSERT INTO NHANVIEN(TENNV, CHUCVU, MANV_QUANLY) VALUES (N'Đinh Văn I', N'Nhân viên', 1);
INSERT INTO NHANVIEN(TENNV, CHUCVU, MANV_QUANLY) VALUES (N'Ngô Thị K', N'Nhân viên', 1);
INSERT INTO NHANVIEN(TENNV, CHUCVU, MANV_QUANLY) VALUES (N'Ngô Thị F', N'Nhân viên', 1);
INSERT INTO NHANVIEN(TENNV, CHUCVU, MANV_QUANLY) VALUES (N'Ngô Thị C', N'Nhân viên', 1);
select * from NHANVIEN





-- Bảng THONGTINNHANVIEN (Thông tin nhân viên)
SET DATEFORMAT DMY
INSERT INTO THONGTINNHANVIEN(MANV, NGAYSINH, GIOITINH, CMND, EMAIL) VALUES (1, '01/01/1990', N'Nam', '012345678901', N'vana@gmail.com');
INSERT INTO THONGTINNHANVIEN(MANV, NGAYSINH, GIOITINH, CMND, EMAIL) VALUES (2, '12/03/1991', N'Nữ', '098765432109', N'bthib@gmail.com');
INSERT INTO THONGTINNHANVIEN(MANV, NGAYSINH, GIOITINH, CMND, EMAIL) VALUES (3, '25/06/1988', N'Nam', '091234567890', N'lhc@gmail.com');
INSERT INTO THONGTINNHANVIEN(MANV, NGAYSINH, GIOITINH, CMND, EMAIL) VALUES (4, '04/07/1985', N'Nam', '094321456789', N'pvd@gmail.com');
INSERT INTO THONGTINNHANVIEN(MANV, NGAYSINH, GIOITINH, CMND, EMAIL) VALUES (5, '15/11/1989', N'Nữ', '096754321098', N'vte@gmail.com');
INSERT INTO THONGTINNHANVIEN(MANV, NGAYSINH, GIOITINH, CMND, EMAIL) VALUES (6, '19/09/1992', N'Nữ', '093123456789', N'vtf@gmail.com');
INSERT INTO THONGTINNHANVIEN(MANV, NGAYSINH, GIOITINH, CMND, EMAIL) VALUES (7, '22/02/1987', N'Nam', '097512345678', N'bvg@gmail.com');
INSERT INTO THONGTINNHANVIEN(MANV, NGAYSINH, GIOITINH, CMND, EMAIL) VALUES (8, '11/05/1994', N'Nữ', '092345671234', N'tth@gmail.com');
INSERT INTO THONGTINNHANVIEN(MANV, NGAYSINH, GIOITINH, CMND, EMAIL) VALUES (9, '08/10/1986', N'Nam', '099123456789', N'dvi@gmail.com');
INSERT INTO THONGTINNHANVIEN(MANV, NGAYSINH, GIOITINH, CMND, EMAIL) VALUES (10, '30/12/1990', N'Nữ', '095432167890', N'ntk@gmail.com');
select * from THONGTINNHANVIEN

-- Bảng HOADON (Hóa đơn)
SET DATEFORMAT DMY
INSERT INTO HOADON(MAHD, NGAYLAP, TRANGTHAI, MAKH, MANV) VALUES ('HD151024001','15/10/2024', N'Đã thanh toán', 1, 2);
INSERT INTO HOADON(MAHD, NGAYLAP, TRANGTHAI, MAKH, MANV) VALUES ('HD161024001','16/10/2024', N'Chưa thanh toán', 2, 3);
INSERT INTO HOADON(MAHD, NGAYLAP, TRANGTHAI, MAKH, MANV) VALUES ('HD171024001','17/10/2024', N'Đã hủy', 3, 4);
INSERT INTO HOADON(MAHD, NGAYLAP, TRANGTHAI, MAKH, MANV) VALUES ('HD181024001','18/10/2024', N'Đã thanh toán', 4, 5);
INSERT INTO HOADON(MAHD, NGAYLAP, TRANGTHAI, MAKH, MANV) VALUES ('HD191024001','19/10/2024', N'Chưa thanh toán', 5, 6);
INSERT INTO HOADON(MAHD, NGAYLAP, TRANGTHAI, MAKH, MANV) VALUES ('HD201024001','20/10/2024', N'Đã hủy', 6, 7);
INSERT INTO HOADON(MAHD, NGAYLAP, TRANGTHAI, MAKH, MANV) VALUES ('HD211024001','21/10/2024', N'Đã thanh toán', 7, 8);
INSERT INTO HOADON(MAHD, NGAYLAP, TRANGTHAI, MAKH, MANV) VALUES ('HD221024001','22/10/2024', N'Chưa thanh toán', 8, 9);
INSERT INTO HOADON(MAHD, NGAYLAP, TRANGTHAI, MAKH, MANV) VALUES ('HD231024001','23/10/2024', N'Đã hủy', 9, 10);
INSERT INTO HOADON(MAHD, NGAYLAP, TRANGTHAI, MAKH, MANV) VALUES ('HD241024001','24/10/2024', N'Đã thanh toán', 10, 1);
select * from HOADON


-- Bảng KHUYENMAI (Khuyến mãi) - 4 dòng
INSERT INTO KHUYENMAI (TENKM, DIEUKIEN_APDUNG, GIAMGIA, MOTA) VALUES (N'Mã giảm giá 10%', 100000, 10, N'Giảm 10% cho hóa đơn từ 100.000 VNĐ trở lên');
INSERT INTO KHUYENMAI (TENKM, DIEUKIEN_APDUNG, GIAMGIA, MOTA) VALUES (N'Mã giảm giá 20%', 200000, 20, N'Giảm 20% cho hóa đơn từ 200.000 VNĐ trở lên');
INSERT INTO KHUYENMAI (TENKM, DIEUKIEN_APDUNG, GIAMGIA, MOTA) VALUES (N'Mã giảm giá 15%', 150000, 15, N'Giảm 15% cho hóa đơn từ 150.000 VNĐ trở lên');
INSERT INTO KHUYENMAI (TENKM, DIEUKIEN_APDUNG, GIAMGIA, MOTA) VALUES (N'Mã giảm giá 25%', 250000, 25, N'Giảm 25% cho hóa đơn từ 250.000 VNĐ trở lên');
INSERT INTO KHUYENMAI (TENKM, DIEUKIEN_APDUNG, GIAMGIA, MOTA) VALUES (N'Mã giảm giá 30%', 300000, 30, N'Giảm 30% cho hóa đơn từ 300.000 VNĐ trở lên');
SELECT * FROM KHUYENMAI

-- Bảng CHITIETKHUYENMAI
INSERT INTO CHITIETKHUYENMAI (MAHD, MAKM, MAHG) VALUES ('HD151024001', 1, NULL);  -- Áp dụng cho toàn bộ hóa đơn
INSERT INTO CHITIETKHUYENMAI (MAHD, MAKM, MAHG) VALUES ('HD161024001', 2, 1);  -- Áp dụng cho sản phẩm có mã hàng 1
INSERT INTO CHITIETKHUYENMAI (MAHD, MAKM, MAHG) VALUES ('HD171024001', 3, 2);  -- Áp dụng cho sản phẩm có mã hàng 2
INSERT INTO CHITIETKHUYENMAI (MAHD, MAKM, MAHG) VALUES ('HD181024001', 4, NULL);  -- Áp dụng cho toàn bộ hóa đơn
INSERT INTO CHITIETKHUYENMAI (MAHD, MAKM, MAHG) VALUES ('HD191024001', 5, 3);  -- Áp dụng cho sản phẩm có mã hàng 3
SELECT * FROM CHITIETKHUYENMAI
-- Bảng LOAIHANG (Loại hàng)
INSERT INTO LOAIHANG(TENLOAI) VALUES (N'Kính cận');
INSERT INTO LOAIHANG(TENLOAI) VALUES (N'Kính thời trang');
INSERT INTO LOAIHANG(TENLOAI) VALUES (N'Kính râm');
INSERT INTO LOAIHANG(TENLOAI) VALUES (N'Kính chống ánh sáng xanh');
INSERT INTO LOAIHANG(TENLOAI) VALUES (N'Kính bảo hộ');
INSERT INTO LOAIHANG(TENLOAI) VALUES (N'Kính mát');
INSERT INTO LOAIHANG(TENLOAI) VALUES (N'Kính phân cực');
INSERT INTO LOAIHANG(TENLOAI) VALUES (N'Kính thể thao');
INSERT INTO LOAIHANG(TENLOAI) VALUES (N'Kính 3D');
INSERT INTO LOAIHANG(TENLOAI) VALUES (N'Kính viễn thị');
SELECT * FROM LOAIHANG

-- Bảng HANGHOA (Hàng hóa)
INSERT INTO HANGHOA(TENHANG, DVT, MALOAI) VALUES (N'Kính Ray-Ban', N'Chiếc', 1);
INSERT INTO HANGHOA(TENHANG, DVT, MALOAI) VALUES (N'Kính Gucci', N'Chiếc', 2);
INSERT INTO HANGHOA(TENHANG, DVT, MALOAI) VALUES (N'Kính Chanel', N'Chiếc', 2);
INSERT INTO HANGHOA(TENHANG, DVT, MALOAI) VALUES (N'Kính Oakley', N'Chiếc', 3);
INSERT INTO HANGHOA(TENHANG, DVT, MALOAI) VALUES (N'Kính Dior', N'Chiếc', 4);
INSERT INTO HANGHOA(TENHANG, DVT, MALOAI) VALUES (N'Kính Levi', N'Chiếc', 1);
INSERT INTO HANGHOA(TENHANG, DVT, MALOAI) VALUES (N'Kính Versace', N'Chiếc', 2);
INSERT INTO HANGHOA(TENHANG, DVT, MALOAI) VALUES (N'Kính Prada', N'Chiếc', 3);
INSERT INTO HANGHOA(TENHANG, DVT, MALOAI) VALUES (N'Kính Burberry', N'Chiếc', 4);
INSERT INTO HANGHOA(TENHANG, DVT, MALOAI) VALUES (N'Kính Polaroid', N'Chiếc', 5);
SELECT * FROM HANGHOA
-- Bảng CHITIETHOADON (Chi tiết hóa đơn)
INSERT INTO CHITIETHOADON(MAHD, MAHG, SOLUONG, GIABAN) VALUES ('HD151024001', 1, 2, 1500000);
INSERT INTO CHITIETHOADON(MAHD, MAHG, SOLUONG, GIABAN) VALUES ('HD161024001', 2, 1, 2000000);
INSERT INTO CHITIETHOADON(MAHD, MAHG, SOLUONG, GIABAN) VALUES ('HD171024001', 3, 3, 3500000);
INSERT INTO CHITIETHOADON(MAHD, MAHG, SOLUONG, GIABAN) VALUES ('HD181024001', 4, 1, 5000000);
INSERT INTO CHITIETHOADON(MAHD, MAHG, SOLUONG, GIABAN) VALUES ('HD191024001', 5, 2, 2500000);
INSERT INTO CHITIETHOADON(MAHD, MAHG, SOLUONG, GIABAN) VALUES ('HD201024001', 6, 1, 1500000);
INSERT INTO CHITIETHOADON(MAHD, MAHG, SOLUONG, GIABAN) VALUES ('HD211024001', 7, 3, 4500000);
INSERT INTO CHITIETHOADON(MAHD, MAHG, SOLUONG, GIABAN) VALUES ('HD221024001', 8, 1, 5000000);
INSERT INTO CHITIETHOADON(MAHD, MAHG, SOLUONG, GIABAN) VALUES ('HD231024001', 9, 2, 3500000);
INSERT INTO CHITIETHOADON(MAHD, MAHG, SOLUONG, GIABAN) VALUES ('HD241024001', 10, 1, 1000000);
SELECT * FROM CHITIETHOADON

-- Bảng NHACC (Nhà cung cấp)
INSERT INTO NHACC(TENNCC, DIACHI, SODT) VALUES (N'Nhà cung cấp A', N'Hà Nội', '0912345678');
INSERT INTO NHACC(TENNCC, DIACHI, SODT) VALUES (N'Nhà cung cấp B', N'Hồ Chí Minh', '0987654321');
INSERT INTO NHACC(TENNCC, DIACHI, SODT) VALUES (N'Nhà cung cấp C', N'Đà Nẵng', '0912345678');
INSERT INTO NHACC(TENNCC, DIACHI, SODT) VALUES (N'Nhà cung cấp D', N'Cần Thơ', '0943214567');
INSERT INTO NHACC(TENNCC, DIACHI, SODT) VALUES (N'Nhà cung cấp E', N'Bình Dương', '0967543212');
INSERT INTO NHACC(TENNCC, DIACHI, SODT) VALUES (N'Nhà cung cấp F', N'Hải Phòng', '0931234567');
INSERT INTO NHACC(TENNCC, DIACHI, SODT) VALUES (N'Nhà cung cấp G', N'Quảng Ninh', '0975123456');
INSERT INTO NHACC(TENNCC, DIACHI, SODT) VALUES (N'Nhà cung cấp H', N'Vũng Tàu', '0991234567');
INSERT INTO NHACC(TENNCC, DIACHI, SODT) VALUES (N'Nhà cung cấp I', N'Hà Tĩnh', '0923456712');
INSERT INTO NHACC(TENNCC, DIACHI, SODT) VALUES (N'Nhà cung cấp J', N'Quảng Bình', '0912345678');
SELECT * FROM NHACC

-- Bảng PHIEUNHAP (Phiếu nhập)
set dateformat dmy
INSERT INTO PHIEUNHAP(MAPN, NGAYNHAP, MANCC, MANV) VALUES ('PN151024001','15/10/2024', 1, 2);
INSERT INTO PHIEUNHAP(MAPN, NGAYNHAP, MANCC, MANV) VALUES ('PN161024001','16/10/2024', 2, 3);
INSERT INTO PHIEUNHAP(MAPN, NGAYNHAP, MANCC, MANV) VALUES ('PN171024001','17/10/2024', 3, 4);
INSERT INTO PHIEUNHAP(MAPN, NGAYNHAP, MANCC, MANV) VALUES ('PN181024001','18/10/2024', 4, 5);
INSERT INTO PHIEUNHAP(MAPN, NGAYNHAP, MANCC, MANV) VALUES ('PN191024001','19/10/2024', 5, 6);
INSERT INTO PHIEUNHAP(MAPN, NGAYNHAP, MANCC, MANV) VALUES ('PN201024001','20/10/2024', 6, 7);
INSERT INTO PHIEUNHAP(MAPN, NGAYNHAP, MANCC, MANV) VALUES ('PN211024001','21/10/2024', 7, 8);
INSERT INTO PHIEUNHAP(MAPN, NGAYNHAP, MANCC, MANV) VALUES ('PN221024001','22/10/2024', 8, 9);
INSERT INTO PHIEUNHAP(MAPN, NGAYNHAP, MANCC, MANV) VALUES ('PN231024001','23/10/2024', 9, 10);
INSERT INTO PHIEUNHAP(MAPN, NGAYNHAP, MANCC, MANV) VALUES ('PN241024001','24/10/2024', 10, 1);
SELECT * FROM PHIEUNHAP

-- Bảng CHITIETPN (Chi tiết phiếu nhập)
INSERT INTO CHITIETPN(MAPN, MAHG, SOLUONG, GIABAN) VALUES ('PN151024001', 1, 10, 1500000);
INSERT INTO CHITIETPN(MAPN, MAHG, SOLUONG, GIABAN) VALUES ('PN161024001', 2, 5, 2000000);
INSERT INTO CHITIETPN(MAPN, MAHG, SOLUONG, GIABAN) VALUES ('PN171024001', 3, 8, 3500000);
INSERT INTO CHITIETPN(MAPN, MAHG, SOLUONG, GIABAN) VALUES ('PN181024001', 4, 7, 5000000);
INSERT INTO CHITIETPN(MAPN, MAHG, SOLUONG, GIABAN) VALUES ('PN191024001', 5, 6, 2500000);
INSERT INTO CHITIETPN(MAPN, MAHG, SOLUONG, GIABAN) VALUES ('PN201024001', 6, 3, 1500000);
INSERT INTO CHITIETPN(MAPN, MAHG, SOLUONG, GIABAN) VALUES ('PN211024001', 7, 12, 4500000);
INSERT INTO CHITIETPN(MAPN, MAHG, SOLUONG, GIABAN) VALUES ('PN221024001', 8, 4, 5000000);
INSERT INTO CHITIETPN(MAPN, MAHG, SOLUONG, GIABAN) VALUES ('PN231024001', 9, 9, 3500000);
INSERT INTO CHITIETPN(MAPN, MAHG, SOLUONG, GIABAN) VALUES ('PN241024001', 10, 11, 1000000);
SELECT * FROM CHITIETPN
--Bảng LICHCA
INSERT INTO LichCa (TENCACAO, THOIGIANBATDAU, THOIGIANKETTHUC) VALUES (N'Ca sáng', '08:00', '12:00')
INSERT INTO LichCa (TENCACAO, THOIGIANBATDAU, THOIGIANKETTHUC) VALUES (N'Ca chiều', '13:00', '17:00')
INSERT INTO LichCa (TENCACAO, THOIGIANBATDAU, THOIGIANKETTHUC) VALUES (N'Ca tối', '18:00', '22:00')
SELECT * FROM LICHCA
--BẢNG LICHTRUC
SET DATEFORMAT DMY
INSERT INTO LICHTRUC(MANV, MACA, NGAYTRUC) VALUES (1, 1, '12/11/2024')
INSERT INTO LICHTRUC(MANV, MACA, NGAYTRUC) VALUES (1, 2, '13/11/2024')
SELECT * FROM LICHTRUC
--BẢNG CHAMCONG
SET DATEFORMAT DMY
INSERT INTO CHAMCONG(MANV, MACA, NGAYLAM, THOIGIANVAO, THOIGIANRA, GHICHU) VALUES(1, 1, '12/11/2024', '8:00', '11:00', N'về sớm có việc nhà')
SELECT * FROM CHAMCONG
-- ALL SELECT TABLE
SELECT * FROM THONGTINNHANVIEN
SELECT * FROM NHANVIEN
SELECT * FROM KHACHHANG
SELECT * FROM HOADON
SELECT * FROM LOAIHANG
SELECT * FROM HANGHOA
SELECT * FROM CHITIETHOADON
SELECT * FROM NHACC
SELECT * FROM PHIEUNHAP
SELECT * FROM CHITIETPN
SELECT * FROM KHUYENMAI
SELECT * FROM CHITIETKHUYENMAI


DELETE FROM THONGTINNHANVIEN
DELETE FROM NHANVIEN
DELETE FROM KHACHHANG
DELETE FROM HOADON
DELETE FROM LOAIHANG
DELETE FROM HANGHOA
DELETE FROM CHITIETHOADON
DELETE FROM NHACC
DELETE FROM PHIEUNHAP
DELETE FROM CHITIETPN
DELETE FROM KHUYENMAI
DELETE FROM CHITIETKHUYENMAI

DBCC CHECKIDENT ('HANGHOA', RESEED, 0);
DBCC CHECKIDENT ('NHANVIEN', RESEED, 0);
DBCC CHECKIDENT ('KHACHHANG', RESEED, 0);
DBCC CHECKIDENT ('HOADON', RESEED, 0);
DBCC CHECKIDENT ('LOAIHANG', RESEED, 0);
DBCC CHECKIDENT ('HANGHOA', RESEED, 0);
DBCC CHECKIDENT ('NHACC', RESEED, 0);
DBCC CHECKIDENT ('PHIEUNHAP', RESEED, 0);
DBCC CHECKIDENT ('KHUYENMAI', RESEED, 0);
DBCC CHECKIDENT ('LICHCA', RESEED, 0);

DROP TABLE CHITIETHOADON
DROP TABLE HOADON
DROP TABLE KHUYENMAI
DROP TABLE CHITIETKHUYENMAI
DROP TABLE CHITIETPN
DROP TABLE PHIEUNHAP



CREATE TABLE UserSessions
(
	UserID NVARCHAR(30)
)

/*=======================================TRUY VẤN DỮ LIỆU==================================*/

--1. Kiểm tra và sử lý hàng tồn kho
--1.1. Kiểm tra số lượng tồn kho của mỗi hàng hóa
CREATE VIEW TONG_NHAP
AS
	SELECT MAHG, SUM(SOLUONG) AS TONG_NHAP
	FROM CHITIETPN
	GROUP BY MAHG
SELECT * FROM TONG_NHAP

CREATE VIEW TONG_BAN
AS
	SELECT MAHG, SUM(SOLUONG) AS TONG_BAN
	FROM CHITIETHOADON
	GROUP BY MAHG
SELECT * FROM TONG_BAN

SELECT TONG_BAN.MAHG,HANGHOA.TENHANG,(TONG_NHAP-TONG_BAN) AS SOLUONGTONKHO
FROM TONG_BAN, TONG_NHAP, HANGHOA
WHERE HANGHOA.MAHG=TONG_BAN.MAHG
AND HANGHOA.MAHG=TONG_NHAP.MAHG
GROUP BY TONG_BAN.MAHG,HANGHOA.TENHANG,(TONG_NHAP-TONG_BAN)

--1.2. Tìm các hàng hóa đã nhập nhưng chưa bán - lồng tương quan
SELECT HANGHOA.MAHG, HANGHOA.TENHANG, TONG_NHAP.TONG_NHAP
FROM HANGHOA 
JOIN TONG_NHAP ON HANGHOA.MAHG = TONG_NHAP.MAHG
WHERE NOT EXISTS (
    SELECT * 
    FROM CHITIETHOADON 
    WHERE CHITIETHOADON.MAHG = HANGHOA.MAHG
)

GO

-- DẠNG THỦ TỤC
CREATE PROC HANG_CHUA_BAN
AS
	BEGIN
		SELECT HANGHOA.MAHG, HANGHOA.TENHANG,DVT, MALOAI, DONGIA, HINH ,TONG_NHAP.TONG_NHAP 
		FROM HANGHOA 
		JOIN TONG_NHAP ON HANGHOA.MAHG = TONG_NHAP.MAHG
		WHERE NOT EXISTS (
			SELECT * 
			FROM CHITIETHOADON 
			WHERE CHITIETHOADON.MAHG = HANGHOA.MAHG
		)
	END
GO

EXEC HANG_CHUA_BAN

GO

--1.3. Hàng hóa có doanh thu cao nhất - lồng phân cấp
SELECT CHITIETHOADON.MAHG, HANGHOA.TENHANG, SUM(CHITIETHOADON.SOLUONG * CHITIETHOADON.GIABAN) AS DOANH_THU
FROM CHITIETHOADON JOIN HANGHOA ON CHITIETHOADON.MAHG = HANGHOA.MAHG
GROUP BY CHITIETHOADON.MAHG, HANGHOA.TENHANG
HAVING SUM(CHITIETHOADON.SOLUONG * CHITIETHOADON.GIABAN) >= ALL (
        SELECT SUM(CHITIETHOADON.SOLUONG * CHITIETHOADON.GIABAN)
        FROM CHITIETHOADON
        GROUP BY CHITIETHOADON.MAHG
    )

GO
-- DẠNG THỦ TỤC 
CREATE PROC HANG_BAN_CHAY_NHAT
AS
	BEGIN
		SELECT CHITIETHOADON.MAHG, HANGHOA.TENHANG ,HANGHOA.DVT, HANGHOA.MALOAI, DONGIA, HINH,SUM(CHITIETHOADON.SOLUONG * CHITIETHOADON.GIABAN) AS DOANH_THU
		FROM CHITIETHOADON JOIN HANGHOA ON CHITIETHOADON.MAHG = HANGHOA.MAHG
		GROUP BY CHITIETHOADON.MAHG, HANGHOA.TENHANG ,HANGHOA.DVT, HANGHOA.MALOAI,DONGIA, HINH
		HAVING SUM(CHITIETHOADON.SOLUONG * CHITIETHOADON.GIABAN) >= ALL (
				SELECT SUM(CHITIETHOADON.SOLUONG * CHITIETHOADON.GIABAN)
				FROM CHITIETHOADON
				GROUP BY CHITIETHOADON.MAHG
    )
	END
GO
EXEC HANG_BAN_CHAY_NHAT

GO

CREATE PROC HANG_CHUA_BAN_VA_TONG
    @TongSoLuongChuaBan INT OUTPUT
AS
BEGIN
    SELECT HANGHOA.MAHG, HANGHOA.TENHANG, DVT, MALOAI,DONGIA, HINH, TONG_NHAP.TONG_NHAP
    FROM HANGHOA
    JOIN TONG_NHAP ON HANGHOA.MAHG = TONG_NHAP.MAHG
    WHERE NOT EXISTS (
        SELECT * 
        FROM CHITIETHOADON
        WHERE CHITIETHOADON.MAHG = HANGHOA.MAHG
    );
    
    -- Tính tổng số lượng hàng chưa bán
    SELECT @TongSoLuongChuaBan = SUM(TONG_NHAP.TONG_NHAP)
    FROM HANGHOA
    JOIN TONG_NHAP ON HANGHOA.MAHG = TONG_NHAP.MAHG
    WHERE NOT EXISTS (
        SELECT * 
        FROM CHITIETHOADON
        WHERE CHITIETHOADON.MAHG = HANGHOA.MAHG
    );
END
GO



GO
--1.4. Khi ta thêm một CHITIETHD mà hàng hóa có số lượng tồn kho thấp hơn mức tối thiểu của hàng hóa đó thì thông báo
SELECT * FROM CHITIETHOADON
SELECT * FROM CHITIETPN

GO
CREATE PROC P_KIEMTRA_TONKHO @MAHD CHAR(20), @MAHG CHAR(20), @SOLUONG INT
AS
	BEGIN
		DECLARE @SOLUONGTONKHO INT
		SET @SOLUONGTONKHO =(SELECT SUM(SOLUONG) FROM  CHITIETPN WHERE MAHG=@MAHG)-(SELECT SUM(SOLUONG) FROM CHITIETHOADON WHERE MAHG=@MAHG)
		-- Kiểm tra sô lượng tồn kho
		IF((@SOLUONGTONKHO) < 0)
			BEGIN
				-- Thông báo lỗi và hủy bỏ việc thêm hóa đơn
				PRINT(N'Số lượng tồn kho của hàng hóa có mã ' +  RTRIM(@MAHG) + N' còn lại '+ CONVERT(NVARCHAR, ABS(@SOLUONGTONKHO + @SOLUONG))+ N' Số lượng không đủ để thêm hóa đơn này. ');
				ROLLBACK
			END

	END
GO



GO
CREATE TRIGGER KT_SOLUONGTONKHO_HH
ON CHITIETHOADON
FOR INSERT, UPDATE
AS
BEGIN
	--Khai báo biến
    DECLARE @MAHG INT,@MAHD CHAR(100),@SOLUONG INT;	
    -- Lấy mã hàng và số lượng từ bản ghi mới được thêm
    SELECT @MAHD=MAHD, @MAHG = MAHG, @SOLUONG = SOLUONG FROM INSERTED;
	EXEC P_KIEMTRA_TONKHO @MAHD, @MAHG, @SOLUONG
END;
GO
DROP TRIGGER KT_SOLUONGTONKHO_HH
GO
-- Test thử việc thêm hóa đơn mà sản phẩm có số lượng tồn kho thấp hơn mức tối thiểu
SELECT * FROM HANGHOA
SELECT * FROM CHITIETPN
SELECT * FROM CHITIETHOADON


INSERT INTO CHITIETHOADON VALUES(2, 1, 97, 800000);

DELETE FROM CHITIETHOADON
WHERE MAHD='HD002' AND MAHG='HG001'
-- Test thử việc thêm hóa đơn mà sản phẩm có số lượng tồưn kho = 0
INSERT INTO CHITIETHOADON VALUES('HD002', 'HG001', 98, 800000);


DELETE FROM CHITIETHOADON
WHERE MAHD='HD002' AND MAHG='HG001'
-- Test thử việc thêm hóa đơn mà sản phẩm có số lượng tồn kho không đủ để đáp ứng
INSERT INTO CHITIETHOADON VALUES('HD002', 'HG001', 99, 800000);



--Test update
UPDATE CHITIETHOADON
SET SOLUONG=99
WHERE MAHD='HD002' AND MAHG='HG001'

-- Kiểm tra CHITIETHOADON
SELECT * FROM CHITIETHOADON



---- 2. NGHIỆP VỤ ĐẶT HÀNG TẠO HÓA ĐƠN
----------------------------------------------------------------------------------------------
---- *LẤY THÔNG TIN CỦA NHỮNG SẢN PHẨM ĐÃ ĐẶT TỪ BẢNG HANGHOA*
---- CÂU TRUY VẤN:

--DECLARE @MaHangDaDat TABLE (MAHG CHAR(15));
--INSERT INTO @MaHangDaDat VALUES ('HG001'), ('HG002');

--SELECT * FROM HANGHOA WHERE MAHG IN (SELECT MAHG FROM @MaHangDaDat);
----------------------------------------------------------------------------------------------

---- *NẾU KHÁCH HÀNG CHƯA CÓ THÔNG TIN TRÊN HỆ THỐNG THÌ THÊM THÔNG TIN VÀO BẢNG KHACHHANG*
---- CÂU TRUY VẤN:

--DECLARE @MaKhachHang NVARCHAR(15) = 'KH004'; -- Ví dụ mã khách hàng mới

--IF EXISTS (SELECT 1 FROM KHACHHANG WHERE MAKH = @MaKhachHang)
--BEGIN
--    -- Nếu khách hàng đã tồn tại, thông báo lỗi
--    RAISERROR('Khách hàng có mã %s đã tồn tại trong hệ thống.', 16, 1, @MaKhachHang);
--END
--ELSE
--BEGIN
--    -- Nếu khách hàng chưa tồn tại, tiến hành thêm mới
--    INSERT INTO KHACHHANG (MAKH, TENKH, DIACHI, SODT)
--    --VALUES (@MaKhachHang, N'Phương Nam Phong Thanh', N'Highlands D10', N'0923603925');
--	VALUES (@MaKhachHang, N'Thanh Phương Nam Phong', N'Highlands Tân Phú', N'0922623975');
--END

--SELECT * FROM KHACHHANG
-----------------------------------------------------------------------------------------------
---- *TẠO BẢN GHI MỚI VÀO BẢNG HOADON*

--DECLARE @MaHoaDonMoi CHAR(15) = 'HD004'; -- Ví dụ mã hóa đơn mới
--DECLARE @NgayLap DATE = GETDATE();
--DECLARE @MaKhachHangMoi NVARCHAR(15) = 'KH004'; -- Thay bằng mã khách hàng thực tế
--DECLARE @MaNhanVienMoi CHAR(15) = 'NV002';

--INSERT INTO HOADON (MAHD, NGAYLAP, TRANGTHAI, MAKH, MANV)
--VALUES (@MaHoaDonMoi, @NgayLap, N'Đang xử lý', @MaKhachHangMoi, @MaNhanVienMoi);

--SELECT * FROM HOADON
-----------------------------------------------------------------------------------------------
---- *THÊM BẢN GHI VÀO BẢNG CHITIETHOADON*

---- Giả sử dữ liệu chi tiết hóa đơn được lưu trữ trong một bảng tạm thời
----DECLARE @MaHoaDonMoi CHAR(15) = 'HD004';
--DECLARE @ChiTietHoaDon TABLE (MAHD CHAR(15), MAHG CHAR(15), SOLUONG INT, GIABAN FLOAT);
--INSERT INTO @ChiTietHoaDon (MAHD, MAHG, SOLUONG, GIABAN) VALUES 
--    (@MaHoaDonMoi, 'HG003', 2, 700000),
--    (@MaHoaDonMoi, 'HG002', 3, 400000);

--INSERT INTO CHITIETHOADON (MAHD, MAHG, SOLUONG, GIABAN)
--SELECT * FROM @ChiTietHoaDon;

-----------------------------------------------------------------------------------------------
---- *TÍNH TỔNG TIỀN*
--DECLARE @MaHoaDon NVARCHAR(15) = 'HD001'; -- Thay bằng mã hóa đơn cần tính

--SELECT SUM(SOLUONG * GIABAN) AS TONGTIEN
--FROM CHITIETHOADON
--WHERE MAHD = @MaHoaDon;

-----------------------------------------------------------------------------------------------
--SELECT HOADON.MAHD, TENKH, SUM(SOLUONG * GIABAN) AS TONGTIEN
--FROM KHACHHANG
--INNER JOIN HOADON ON KHACHHANG.MAKH = HOADON.MAKH
--INNER JOIN CHITIETHOADON ON HOADON.MAHD = CHITIETHOADON.MAHD
--GROUP BY HOADON.MAHD, TENKH


-- CÁCH KHÔNG ĐẶT BIẾN - TRUY VẤN DEMO
-- 1. Lấy thông tin những mã hàng mà khách đã đặt show ra chi tiết
SELECT * FROM HANGHOA
WHERE MAHG = 'HG005' --

-- 2. Kiểm tra nếu khách hàng chưa có trong bảng KHACHHANG thì thêm mới vào
IF EXISTS (SELECT 1 FROM KHACHHANG WHERE MAKH = 'KH004')
BEGIN 
	RAISERROR('Khách hàng có mã %s đã tồn tại trong hệ thống.', 16, 1, 'KH004');
END
ELSE 
BEGIN
	INSERT INTO KHACHHANG (MAKH, TENKH, DIACHI, SODT)
    VALUES ('KH004', N'Nguyễn Thị D', N'Highlands D10', N'0923603925');
END	

SELECT * FROM KHACHHANG

-- 3. Thêm một hóa đơn mới vào bảng HOADON
INSERT INTO HOADON (MAHD, NGAYLAP, TRANGTHAI, MAKH, MANV)
VALUES ('HD004', '2024-8-31', N'Đang xử lý', 'KH004', 'NV001');

SELECT * FROM HOADON

-- 4. Thêm vào bảng CHITIETHD
INSERT INTO CHITIETHOADON (MAHD, MAHG, SOLUONG, GIABAN)
VALUES ('HD004', 'HG005', 1, 180000)

-- 5. Tính tổng tiền
SELECT HOADON.MAHD, TENKH, SUM(SOLUONG * GIABAN) AS TONGTIEN
FROM KHACHHANG
INNER JOIN HOADON ON KHACHHANG.MAKH = HOADON.MAKH
INNER JOIN CHITIETHOADON ON HOADON.MAHD = CHITIETHOADON.MAHD
GROUP BY HOADON.MAHD, TENKH


-- CÁCH ĐẶT BIẾN
DECLARE @MaHangDaDat TABLE (MAHG CHAR(15)); -- Bảng chứa mã hàng đã đặt
DECLARE @MaHoaDonMoi CHAR(15) = 'HD004'; -- Ví dụ mã hóa đơn này là một hóa đơn mới
DECLARE @NgayLap DATE = GETDATE(); -- Lấy ngày hiện tại
DECLARE @MaKhachHangMoi NVARCHAR(15) = 'KH004'; -- Lấy mã khách hàng của KH mới, sau này thay bằng mã khách hàng thực tế
DECLARE @MaNhanVienMoi CHAR(15) = 'NV001'; -- Mã nhân viên mà lập ra hóa đơn này
DECLARE @ChiTietHoaDon TABLE (MAHD CHAR(15), MAHG CHAR(15), SOLUONG INT, GIABAN FLOAT); 
-- Bảng chứa thông tin chi tiết của hóa đơn


-- 1. Lấy thông tin những mã hàng mà khách đã đặt show ra chi tiết
INSERT INTO @MaHangDaDat VALUES ('HG005'), ('HG007'); -- Giả sử mã hàng đã đặt gồm có HG001 và HG002
SELECT * FROM HANGHOA WHERE MAHG IN (SELECT MAHG FROM @MaHangDaDat);


-- 2. Kiểm tra nếu khách hàng chưa có trong bảng KHACHHANG thì thêm mới vào
IF EXISTS (SELECT 1 FROM KHACHHANG WHERE MAKH = @MaKhachHangMoi)
BEGIN
    -- Nếu khách hàng đã tồn tại, thông báo lỗi
    RAISERROR('Khách hàng có mã %s đã tồn tại trong hệ thống.', 16, 1, @MaKhachHangMoi);
END

ELSE
BEGIN
    -- Nếu khách hàng chưa tồn tại, tiến hành thêm mới
    INSERT INTO KHACHHANG (MAKH, TENKH, DIACHI, SODT)
    --VALUES (@MaKhachHang, N'Phương Nam Phong Thanh', N'Highlands D10', N'0923603925');
	VALUES (@MaKhachHangMoi, N'Thanh Phương Nam Phong', N'Highlands Tân Phú', N'0922623975');
END


-- 3. Thêm một hóa đơn mới vào bảng HOADON
INSERT INTO HOADON (MAHD, NGAYLAP, TRANGTHAI, MAKH, MANV)
VALUES (@MaHoaDonMoi, @NgayLap, N'Đang xử lý', @MaKhachHangMoi, @MaNhanVienMoi);

SELECT * FROM HOADON


-- 4. Thêm vào bảng CHITIETHD
INSERT INTO @ChiTietHoaDon (MAHD, MAHG, SOLUONG, GIABAN) VALUES 
    (@MaHoaDonMoi, 'HG005', 2, 700000),
    (@MaHoaDonMoi, 'HG007', 3, 400000);

INSERT INTO CHITIETHOADON (MAHD, MAHG, SOLUONG, GIABAN)
SELECT MAHD, MAHG, SOLUONG, GIABAN
FROM @ChiTietHoaDon;

SELECT * FROM CHITIETHOADON;


-- 5. Tính tổng tiền
DECLARE @MaHoaDon NVARCHAR(15) = 'HD001'; -- Thay bằng mã hóa đơn cần tính

SELECT SUM(SOLUONG * GIABAN) AS TONGTIEN
FROM CHITIETHOADON
WHERE MAHD = @MaHoaDon;

-----------------------------------------------------------------------------------------------

GO

-- 1. TẠO THỦ TỤC CHO BẢNG KHACHHANG 
-- 1.1. Hiển thị thông tin khách hàng
CREATE PROC DISPLAY_KHACHHANG 
AS
	SELECT * FROM KHACHHANG

--EXEC DISPLAY_KHACHHANG 

GO
-- 1.2. Thêm một khách hàng
--@"INSERT INTO KHACHHANG(MAKH, TENKH, DIACHI, SODT) 
--VALUES('" + txtmakh.Text + "',N'" + txttenkh.Text 
-- + "',N'" + txtdiachi.Text + "','" + txtsodt.Text + "')";

CREATE PROC INSERT_KHACHHANG @TENKH NVARCHAR(50), @DIACHI NVARCHAR(50), @SODT CHAR (10)
AS
	INSERT INTO KHACHHANG VALUES(@TENKH, @DIACHI, @SODT)

-- EXEC INSERT_KHACHHANG 'KH007', N'Bùi Thị D', N'Dak Nong', '0989712346'
-- EXEC INSERT_KHACHHANG "'" + txtmakh.Text + "', N'" + txttenkh.Text + "', N'" + txtdiachi.Text + "', '" + txtsodt.Text + "'"

GO
-- 1.3. Xóa một khách hàng
CREATE PROC DELETE_KHACHHANG @MAKH INT
AS
	DELETE FROM KHACHHANG WHERE MAKH = @MAKH

--"DELETE FROM KHACHHANG WHERE MAKH = '"+txtmakh.Text+"'"
EXEC DELETE_KHACHHANG 'KH001'
-- "EXEC DELETE_KHACHHANG '" + txtmakh.Text + "'"
GO
-- 1.4. Sửa một khách hàng
CREATE PROC UPDATE_KHACHHANG @MAKH_OLD INT, @TENKH NVARCHAR(50), @DIACHI NVARCHAR(50), @SODT CHAR(10)
AS 
	UPDATE KHACHHANG
	SET TENKH = @TENKH, DIACHI = @DIACHI, SODT = @SODT
	WHERE MAKH = @MAKH_OLD

--"UPDATE KHACHHANG SET MAKH = '"+txtmakh.Text+"',TENKH = N'"+txttenkh.Text+"',
--DIACHI = N'"+txtdiachi.Text+"',SODT = '"+txtsodt.Text+"' WHERE MAKH='"
--+item.SubItems[0].Text+"'"

EXEC UPDATE_KHACHHANG 'KH001', 'KH007', N'Trần Thị Thanh Phong', N'Cà Mau', '0976542917'
-- "EXEC UPDATE_KHACHHANG '" + txtmakh.Text + "', '" + item.SubItems[0].Text + "', N'" + txttenkh.Text + "', N'" + txtdiachi.Text + "', '" + txtsodt.Text + "'"

GO
-- 2. TẠO THỦ TỤC CHO VIEW HOADON
-- 2.1. Hiển thị thông tin hóa đơn
CREATE VIEW	HOADON_VIEW
AS 
	SELECT * FROM HOADON

GO

CREATE PROC DISPLAY_HOADON_VIEW
AS
	SELECT * FROM HOADON_VIEW

EXEC DISPLAY_HOADON_VIEW

GO
-- 2.2. Thêm một hóa đơn
CREATE PROC INSERT_HOADON_VIEW @NGAYLAP DATE, @TRANGTHAI NVARCHAR(30), @MAKH INT, @MANV INT
AS
	INSERT INTO HOADON_VIEW(NGAYLAP, TRANGTHAI, MAKH, MANV) VALUES (@NGAYLAP, @TRANGTHAI, @MAKH, @MANV)

GO

-- EXEC INSERT_HOADON_VIEW 'HD001', '2024/09/10', N'Còn hàng', 'KH001', 'NV002'
-- 2.3. Xóa một hóa đơn
CREATE PROC DELETE_HOADON_VIEW @MAHD INT
AS	
	DELETE 
	FROM HOADON_VIEW 
	WHERE MAHD = @MAHD

GO

-- EXEC DELETE_HOADON_VIEW 'HD003'
-- 2.4. Sửa một hóa đơn
CREATE PROC UPDATE_HOADON_VIEW @MAHD_OLD CHAR(10), @NGAYLAP DATE, @TRANGTHAI NVARCHAR(30), @MAKH INT, @MANV INT
AS
	UPDATE HOADON_VIEW
	SET NGAYLAP = @NGAYLAP, TRANGTHAI = @TRANGTHAI, MAKH = @MAKH, MANV = @MANV
	WHERE MAHD = @MAHD_OLD

-- EXEC UPDATE_HOADON_VIEW 'HD001', 'HD007', '2024/09/10', N'Còn hàng', 'KH001', 'NV001'

GO
-- 3. TẠO THỦ TỤC CHO BẢNG 
CREATE VIEW NHANVIEN_COPY
AS
	SELECT * FROM NHANVIEN

GO
-- 3.1. Hiển thị thông tin bảng nhanvien
CREATE PROC DISPLAY_NHANVIEN_VIEW 
AS 
	SELECT * FROM NHANVIEN_COPY

EXEC DISPLAY_NHANVIEN

GO
-- 3.2. Thêm một nhân viên
CREATE PROC INSERT_NHANVIEN_VIEW @TENNV NVARCHAR(50), @CHUCVU NVARCHAR(30), @MANV_QUANLY INT
AS
	INSERT INTO NHANVIEN_COPY VALUES (@TENNV, @CHUCVU, @MANV_QUANLY)

--EXEC INSERT_NHANVIEN_VIEW
GO

-- 3.3. Xóa một nhân viên
CREATE PROC DELETE_NHANVIEN_VIEW @MANV INT
AS
	DELETE
	FROM NHANVIEN_COPY
	WHERE MANV = @MANV

GO
-- 3.4. Sửa một nhân viên

CREATE PROC UPDATE_NHANVIEN_VIEW @MANV_OLD INT, @TENNV NVARCHAR(50), @CHUCVU NVARCHAR(30), @MANV_QUANLY INT
AS
	--IF NOT EXISTS(SELECT 1 FROM NHANVIEN_COPY WHERE MANV = @MANV_OLD)
	UPDATE NHANVIEN_COPY 
	SET TENNV = @TENNV, CHUCVU = @CHUCVU, MANV_QUANLY = @MANV_QUANLY 
	WHERE MANV = @MANV_OLD

EXEC UPDATE_NHANVIEN_VIEW 'NV0013', 'NV002', N'NGUYENVAN2', N'GIAMDOC2', 'NV003'
SELECT * FROM NHANVIEN_COPY

GO

-- 4. TẠO THỦ TỤC CHO BẢNG HANGHOA
-- 4.1. Hiển thị thông tin hàng hóa
CREATE PROC DISPLAY_HANGHOA
AS
	SELECT * FROM HANGHOA

EXEC DISPLAY_HANGHOA 

GO
-- 4.2. Thêm một hàng hóa
CREATE PROC INSERT_HANGHOA @TENHANG NVARCHAR(50), @DVT NVARCHAR(30), @MALOAI INT, @DONGIA FLOAT, @HINH NVARCHAR(100)
AS
	INSERT INTO HANGHOA(TENHANG, DVT, MALOAI, DONGIA, HINH) VALUES (@TENHANG, @DVT, @MALOAI, @DONGIA, @HINH)
	
GO

-- 4.3. Xóa một hàng hóa
CREATE PROC DELETE_HANGHOA (@MAHG INT)
AS
	DELETE
	FROM HANGHOA
	WHERE MAHG = @MAHG

GO
EXEC DELETE_HANGHOA '12'
SELECT * FROM HANGHOA
-- 4.4. Sửa một hàng hóa
CREATE PROC UPDATE_HANGHOA @MAHG_OLD INT, @TENHANG NVARCHAR(50), @DVT NVARCHAR(30), @MALOAI INT,@DONGIA FLOAT, @HINH NVARCHAR(100)
AS
	UPDATE HANGHOA
	SET TENHANG = @TENHANG, DVT = @DVT, MALOAI = @MALOAI , DONGIA=@DONGIA, HINH=@HINH
	WHERE MAHG = @MAHG_OLD

EXEC UPDATE_HANGHOA '15',N'huhu',N'hihi','7'

SELECT * FROM HANGHOA


--/*=====================================================================BẢNG HÓA ĐƠN========================================================================*/
CREATE PROC HIENTHI_HOADON
AS
	BEGIN
		SELECT * FROM HOADON
	END
GO
 sql = @"EXEC HIENTHI_HOADON";



 CREATE PROC THEM_HOADON @MAHD CHAR(100), @NGAYLAP DATE, @TRANGTHAI NVARCHAR(30), @MAKH INT, @MANV INT
AS
	BEGIN
		INSERT INTO HOADON(MAHD, NGAYLAP, TRANGTHAI, MAKH, MANV) VALUES(@MAHD, @NGAYLAP, @TRANGTHAI, @MAKH, @MANV)
	END
GO
 sql = @"EXEC THEM_HOADON '"+txtmahd.Text.Trim() + "', '"+txtngaylap.Text.Trim()+"', N'"+cbotrangthai.Text.Trim() +"', '"+txtmakh.Text.Trim() +"', '"+txtmanv.Text.Trim() +"'";



CREATE PROC XOA_HOADON @MAHD CHAR(100)
AS
	BEGIN
		DELETE FROM HOADON WHERE MAHD = @MAHD
	END
GO
 sql = @"EXEC XOA_HOADON '"+txtmahd.Text.Trim() +"'";
GO


CREATE PROC SUA_HOADON @NGAYLAP DATE, @TRANGTHAI NVARCHAR(30), @MAKH INT, @MANV INT, @TAM CHAR(100)
AS
	BEGIN
		UPDATE HOADON SET NGAYLAP = @NGAYLAP, TRANGTHAI = @TRANGTHAI, MAKH = @MAKH, MANV = @MANV WHERE MAHD = @TAM
	END
GO
 string sql = @"EXEC SUA_HOADON '" + txtmahd.Text.Trim() + "','" + txtngaylap.Text.Trim() + "', N'" + cbotrangthai.Text.Trim() + "', '" + txtmakh.Text.Trim() + "', '" + txtmanv.Text.Trim() + "', '" + item.SubItems[0].Text + "'";
/*=====================================================================BẢNG NHÂN VIÊN========================================================================*/
CREATE PROC HIENTHI_NHANVIEN
AS
	BEGIN
		SELECT * FROM NHANVIEN
	END
GO
sql = @"EXEC HIENTHI_NHANVIEN";




CREATE PROC THEM_NHANVIEN @TENNV NVARCHAR(30), @CHUCVU NVARCHAR(30), @MNQL INT
AS
	BEGIN
		INSERT INTO NHANVIEN(TENNV, CHUCVU, MANV_QUANLY) VALUES(@TENNV, @CHUCVU, @MNQL)
	END
GO
EXEC THEM_NHANVIEN N'NGUYỄN VĂN G',N'NHÂN VIÊN',1
EXEC THEM_NHANVIEN N'NGUYỄN VĂN F',N'NHÂN VIÊN','2'
 sql = @"EXEC THEM_NHANVIEN '"+txtmanv.Text.Trim() +"', N'"+txttennv.Text.Trim() +"', N'"+txtchucvu.Text.Trim() +"', '"+txtnguoiql.Text.Trim() +"'";



CREATE PROC SUA_NHANVIEN @TENNV NVARCHAR(30), @CHUCVU NVARCHAR(30), @MNQL INT, @TAM INT
AS
	BEGIN
		UPDATE NHANVIEN SET TENNV = @TENNV, CHUCVU = @CHUCVU, MANV_QUANLY = @MNQL WHERE MANV = @TAM 
	END
GO
  string sql = @"EXEC SUA_NHANVIEN '" + txtmanv.Text.Trim() + "', N'" + txttennv.Text.Trim() + "', N'" + txtchucvu.Text.Trim() + "', '" + txtnguoiql.Text.Trim() + "', '" + item.SubItems[0].Text + "'";
/*=====================================================================BẢNG VIEW khách hàng==================================================================*/
CREATE PROC HIENTHI_KHACHHANG_VIEW 
AS
	BEGIN
		SELECT * FROM KHACHHANG_VIEW
	END
GO
  sql = @"EXEC HIENTHI_KHACHHANG_VIEW";


GO
CREATE PROC THEM_KHACH_VIEW @TENKH NVARCHAR(30), @DIACHI NVARCHAR(30), @SODT CHAR(15)
AS
	BEGIN
		INSERT INTO KHACHHANG_VIEW(TENKH, DIACHI, SODT) VALUES(@TENKH, @DIACHI, @SODT)
	END
GO
 sql = @"EXEC THEM_KHACH_VIEW '"+txtmakh.Text.Trim()+"', N'"+txttenkh.Text.Trim() + "', N'"+txtdiachi.Text.Trim() + "', '"+txtdiachi.Text.Trim() + "'";




CREATE PROC XOA_KHACH_VIEW @MAKH INT
AS
	BEGIN
		DELETE FROM KHACHHANG_VIEW WHERE MAKH = @MAKH
	END
GO
sql = @"EXEC XOA_KHACH_VIEW '"+txtmakh.Text.Trim() + "'";


CREATE PROC SUA_KHACHHANG_VIEW @TENKH NVARCHAR(30), @DIACHI NVARCHAR(30), @SODT NVARCHAR(30), @TAM INT
AS
	BEGIN
		UPDATE KHACHHANG_VIEW SET TENKH =@TENKH, DIACHI =@DIACHI, SODT = @SODT WHERE MAKH = @TAM
	END
GO
sql = @"EXEC SUA_KHACHHANG_VIEW '" + txtmakh.Text.Trim() + "', N'" + txttenkh.Text.Trim() + "',N'" + txtdiachi.Text.Trim() + "', '" + txtsodt.Text.Trim() + "','" + item.SubItems[0].Text + "'";
/*=====================================================================BẢNG Hàng Hóa==================================================================*/
CREATE PROC HIENTHI_HANGHOA
AS
	BEGIN
		SELECT * FROM HANGHOA
	END
GO
sql = @"EXEC HIENTHI_HANGHOA";



CREATE PROC THEM_HANGHOC @TENHG NVARCHAR(30), @DVT NVARCHAR(30), @MALOAI INT
AS
	BEGIN
		INSERT INTO HANGHOA(TENHANG, DVT, MALOAI) VALUES(@TENHG, @DVT, @MALOAI)
	END
GO
sql = @"EXEC THEM_HANGHOA '" + txtmahg.Text.Trim()+"', N'"+txttenhang.Text.Trim()+"', N'"+txtdvt.Text.Trim() + "', '"+txtmaloai.Text.Trim() + "'";



CREATE PROC XOA_HANGHOA @MAHG INT
AS
	BEGIN
		DELETE FROM HANGHOA WHERE MAHG=@MAHG
	END
GO
sql = @"EXEC XOA_HANGHOA '"+txtmahg.Text+"'";


CREATE PROC SUA_HANGHOA @TENHANG NVARCHAR(30), @DVT NVARCHAR(30), @MALOAI INT, @TAM INT
AS
	BEGIN
		UPDATE HANGHOA SET TENHANG = @TENHANG, DVT = @DVT, MALOAI = @MALOAI WHERE MAHG = @TAM
	END
GO
string sql = @"EXEC SUA_HANGHOA '"+ txtmahg.Text.Trim() + "', N'@"+ txttenhang.Text.Trim() + "', N'"+ txtdvt.Text.Trim() + "', '"+ txtmaloai.Text.Trim() + "', '" + item.SubItems[0].Text + "'";



-- TẠO THỦ TỤC BÊN LOGIN.CS - ĐỂ THÊM VÀO BẢNG USERSESSIONS 
create proc UserSessions_insert @ID nvarchar(100)
as
	begin		
		DECLARE @sql NVARCHAR(MAX);
		insert into UserSessions values(@ID)
	end
go

-- TẠO THỦ TỤC CHO BẢNG CHITIETHD
--Hiển thị
go
create proc HIENTHI_CHITIETHOADON
as
	begin
		SELECT * FROM CHITIETHOADON
	end
go
EXEC HIENTHI_CHITIETHOADON
--Thêm
go
CREATE proc THEM_CHITIETHOADON @MAHD CHAR(100), @MAHG INT, @SL INT, @GIABAN FLOAT
as
	begin
		INSERT INTO CHITIETHOADON(MAHD, MAHG, SOLUONG, GIABAN) VALUES(@MAHD, @MAHG,@SL,@GIABAN)
	end
go
EXEC THEM_CHITIETHOADON 'HD005', 'HG002', 7, 450000
--Xóa
go
CREATE proc XOA_CHITIETHOADON @MAHD CHAR(100), @MAHG INT
as
	begin
		DELETE FROM CHITIETHOADON WHERE MAHD = @MAHD AND MAHG = @MAHG
	end
go
EXEC XOA_CHITIETHOADON 'HD005', 'HG002'
--Sửa
go
CREATE proc SUA_CHITIETHOADON @MAHD CHAR(100), @MAHG INT, @SL INT, @GIABAN FLOAT, @MAHD_TAM CHAR(100), @MAHG_TAM CHAR(100)
as
	begin
		UPDATE CHITIETHOADON SET MAHD = @MAHD, MAHG = @MAHG, SOLUONG = @SL, GIABAN = @GIABAN WHERE MAHD = @MAHD_TAM AND MAHG = @MAHG_TAM
	end
go
EXEC SUA_CHITIETHOADON 'HD005', 'HG003',5,475000, 'HD005', 'HG002'

GO

--TẠO HÀM ĐỂ LẤY RA BẢNG CHỨA CÁC USER_ID ĐÃ ĐĂNG NHẬP (ĐỂ LÀM NGHIỆP VỤ LOGOUT)
CREATE FUNCTION GET_USER_ID(@USER_ID CHAR(30))
RETURNS TABLE
AS
	RETURN(SELECT * FROM UserSessions WHERE UserID = @USER_ID)

GO

SELECT * FROM dbo.GET_USER_ID('nam3')

GO

-- TẠO THỦ TỤC ĐỂ XÓA TẤT CẢ CÁC
CREATE PROC DELETE_ALL_USERNAME_IN_USERSESSIONS @USER_ID CHAR(30)
AS
BEGIN 
	DELETE FROM UserSessions WHERE UserID = @USER_ID 
END

EXEC DELETE_ALL_USERNAME_IN_USERSESSIONS 'nam3'

GO

-- TẠO THỦ TỤC CHO NÚT EXPORT ĐỂ LẤY DỮ LIỆU TỪ BẢNG
CREATE PROC EXPORT_FROM_ANY_TABLE @TABLE_NAME CHAR(50)
AS
BEGIN
	DECLARE @SQL NVARCHAR(MAX)

	SET @SQL = 'SELECT * FROM ' + @TABLE_NAME;

	EXEC (@SQL); -- nếu không có dấu ( ) thì exec sẽ chạy như một stored procedure: exec '...'
	-- tức là nó sẽ hiểu đây là tên đối tượng
	-- còn nếu có dấu ( ) thì nó sẽ hiểu đây là câu lệnh sql và chỉ chạy chuỗi SQL bên trong dấu ( ) thôi
END

EXEC EXPORT_FROM_ANY_TABLE 'CHITIETPN'


GO
-- TẠO THỦ TỤC ĐỂ IMPORT VÀO MỘT NEW TABLE
CREATE PROC IMPORT_NEW_TABLE_CHECK_EXIST @TABLE_NAME CHAR(50)
AS
BEGIN
	DECLARE @SQL NVARCHAR(MAX);

    SET @SQL = N'IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = ''' + @TABLE_NAME + '''
                                )
                                BEGIN
                                    CREATE TABLE ' + @TABLE_NAME + ' ('

    EXEC (@SQL);
END

GO

ALTER PROC IMPORT_NEW_TABLE_CHECK_EXIST 
    @TABLE_NAME NVARCHAR(128) -- Sử dụng NVARCHAR cho tên bảng
AS
BEGIN
    DECLARE @SQL NVARCHAR(MAX);

    -- Sử dụng QUOTENAME để bao tên bảng trong ngoặc vuông và tránh lỗi SQL Injection
    SET @SQL = N'IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = ' + QUOTENAME(@TABLE_NAME, '''') + N')
                BEGIN
                    CREATE TABLE ' + QUOTENAME(@TABLE_NAME) + N' ('

    EXEC sp_executesql @SQL;
END
GO


EXEC IMPORT_NEW_TABLE_CHECK_EXIST ''
GO
ALTER PROC IMPORT_NEW_TABLE_CHECK_EXIST 
    @TABLE_NAME NVARCHAR(128), 
    @COLUMNS_DEFINITION NVARCHAR(MAX) -- Tham số chứa định nghĩa cột
AS
BEGIN
    DECLARE @SQL NVARCHAR(MAX);

    -- Xây dựng câu lệnh SQL động để tạo bảng nếu bảng chưa tồn tại
    SET @SQL = N'IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = ' + QUOTENAME(@TABLE_NAME, '''') + N')
                BEGIN
                    CREATE TABLE ' + QUOTENAME(@TABLE_NAME) + N' (
                        ' + @COLUMNS_DEFINITION + N'
                    );
                END';

    -- Thực thi câu lệnh SQL động
    EXEC sp_executesql @SQL;
END
GO

-- TẠO THỦ TỤC CHO BẢNG THONGTINNHANVIEN
-- 1. DISPLAY THONGTINNHANVIEN
CREATE PROC DISPLAY_THONGTINNHANVIEN
AS
BEGIN	
	SELECT * FROM THONGTINNHANVIEN
END

EXEC DISPLAY_THONGTINNHANVIEN

-- 2. INSERT THONGTINNHANVIEN
SELECT * FROM THONGTINNHANVIEN
GO
CREATE PROC INSERT_THONGTINNHANVIEN @MANV INT, @NGAYSINH DATE, @GIOITINH NVARCHAR(5), @CMND CHAR(10), @EMAIL CHAR(30)
AS
BEGIN
	INSERT INTO THONGTINNHANVIEN(MANV, NGAYSINH, GIOITINH, CMND, EMAIL) VALUES(@MANV, @NGAYSINH, @GIOITINH, @CMND, @EMAIL)
END

EXEC INSERT_THONGTINNHANVIEN 'MANV VI DU', '10-10-2000', N'NAM', 'CMD09090', 'EMAILNE'

GO
-- 3. DELETE THONGTINNHANVIEN
CREATE PROC DELETE_THONGTINNHANVIEN @MANV INT
AS
BEGIN
	DELETE FROM THONGTINNHANVIEN WHERE MANV = @MANV
END

EXEC DELETE_THONGTINNHANVIEN 'NV001'
GO
-- 4. UPDATE THONGTINNHANVIEN
CREATE PROC UPDATE_THONGTINNHANVIEN @MANV_OLD INT, @MANV_NEW CHAR(10), @NGAYSINH DATE, @GIOITINH NVARCHAR(5), @CMND CHAR(10), @EMAIL CHAR(30)
AS
BEGIN
	SET DATEFORMAT DMY;
	UPDATE THONGTINNHANVIEN SET MANV = @MANV_NEW, NGAYSINH = @NGAYSINH, GIOITINH = @GIOITINH, CMND = @CMND, EMAIL = @EMAIL WHERE MANV = @MANV_OLD
END

EXEC UPDATE_THONGTINNHANVIEN 'NV004', 'NV004', '10-10-2000', N'NAM', '09340923', 'jasdas@gmail.com'
GO
SELECT * FROM THONGTINNHANVIEN

--Tạo hàm CHITIETPN
--Hiển thị
GO
create function F_HIENTHI_CHITIETPN()
returns table
as
	return (SELECT * FROM CHITIETPN)
go

select * from dbo.F_HIENTHI_CHITIETPN()
--Thêm
go
CREATE proc THEM_CHITIETPN(@MAPN CHAR(100), @MAHG char(20), @SOLUONG int, @GIABAN float)
as
	begin
		INSERT INTO CHITIETPN(MAPN, MAHG, SOLUONG, GIABAN) VALUES(@MAPN, @MAHG, @SOLUONG, @GIABAN)
	end
go
EXEC THEM_CHITIETPN 'PN002', 'HG004', 15, 175000
go
--Xóa
CREATE proc XOA_CHITIETPN(@MAPN CHAR(100), @MAHG CHAR(20))
as
	begin
		DELETE FROM CHITIETPN WHERE MAPN = @MAPN AND MAHG = @MAHG
	end
go
EXEC XOA_CHITIETPN 'PN002', 'HG004'
--Sửa
go
CREATE proc SUA_CHITIETPN(@MAPN CHAR(100),@MAHG INT,@SOLUONG int,@GIABAN float,@MAPN_TAM CHAR(100),@MAHG_TAM INT)
as
	begin
		UPDATE CHITIETPN SET MAPN = @MAPN, MAHG = @MAHG, SOLUONG = @SOLUONG, GIABAN = @GIABAN WHERE MAPN = @MAPN_TAM AND MAHG = @MAHG_TAM
	end
go
EXEC SUA_CHITIETPN 'PN002', 'HG005', 30, 1750000, 'PN002', 'HG005'
--Thủ tục PHIEUNHAP
--Hiển thị
GO
create function F_HIENTHI_PHIEUNHAP()
returns table
as
	return (SELECT * FROM PHIEUNHAP)
go
select * from dbo.F_HIENTHI_PHIEUNHAP()
--Thêm
go
SET DATEFORMAT DMY
go
CREATE proc THEM_PHIEUNHAP(@MAPN CHAR(100), @NGAYNHAP date, @MANCC INT, @MANV INT)
as
	begin
		INSERT INTO PHIEUNHAP(MAPN, NGAYNHAP, MANCC, MANV) VALUES(@MAPN, @NGAYNHAP, @MANCC, @MANV)
	end
go
EXEC THEM_PHIEUNHAP 'PN003', '02/07/2023', 'NCC002', 'NV004'
go
--Xóa
CREATE proc XOA_PHIEUNHAP(@MAPN CHAR(100))
as
	begin
		DELETE FROM PHIEUNHAP WHERE MAPN = @MAPN
	end
go
EXEC XOA_PHIEUNHAP 'PN003'
--Sửa
go
SET DATEFORMAT DMY
go
CREATE proc SUA_PHIEUNHAP(@NGAYNHAP date, @MANCC INT, @MANV INT, @MAPN_TAM CHAR(100))
as
	begin
		UPDATE PHIEUNHAP SET NGAYNHAP = @NGAYNHAP, MANCC = @MANCC, MANV = @MANV WHERE MAPN = @MAPN_TAM
	end
go
EXEC SUA_PHIEUNHAP 'PN003', '02/07/2023', 'NCC002', 'NV001', 'PN003'
go
--Thủ tục NHACC
--Hiển thị
GO
create function F_HIENTHI_NHACC()
returns table
as
	return (SELECT * FROM NHACC)
go
select * from dbo.F_HIENTHI_NHACC()
--Thêm
go
SET DATEFORMAT DMY
go
create proc THEM_NHACC(@TENNCC nvarchar(30), @DIACHI nvarchar(20), @SODT char(20))
as
	begin
		INSERT INTO NHACC(TENNCC, DIACHI, SODT) VALUES(@TENNCC, @DIACHI, @SODT)
	end
go
EXEC THEM_NHACC 'NCC003', N'Công ty C', N'Cà Mau', '0922345678'
go
--Xóa
create proc XOA_NHACC(@MANCC INT)
as
	begin
		DELETE FROM NHACC WHERE MANCC = @MANCC
	end
go
EXEC XOA_NHACC 'NCC003'
--Sửa
go
SET DATEFORMAT DMY
go
create proc SUA_NHACC(@TENNCC nvarchar(30), @DIACHI nvarchar(30), @SODT char(20), @MANCC_TAM INT)
as
	begin
		UPDATE NHACC SET TENNCC = @TENNCC, DIACHI = @DIACHI, SODT = @SODT WHERE MANCC = @MANCC_TAM
	end
go
EXEC SUA_NHACC 'NCC002', N'Công ty C', N'Cà Mau', '0912345679', 'NCC002'
go

--Tạo thủ tục LOAIHANG
--Hiển thị
GO
create function F_HIENTHI_LOAIHANG()
returns table
as
	return (SELECT * FROM LOAIHANG)
go
select * from dbo.F_HIENTHI_LOAIHANG()
--Thêm
go
SET DATEFORMAT DMY
go
create proc THEM_LOAIHANG(@TENLOAI nvarchar(30))
as
	begin
		INSERT INTO LOAIHANG(TENLOAI) VALUES(@TENLOAI)
	end
go
EXEC THEM_LOAIHANG 'LT005', N'Kính răm'
go
--Xóa
create proc XOA_LOAIHANG(@MALOAI int)
as
	begin
		DELETE FROM LOAIHANG WHERE MALOAI = @MALOAI
	end
go
EXEC XOA_LOAIHANG 'LT005'
--Sữa
go
SET DATEFORMAT DMY
go
create proc SUA_LOAIHANG(@TENLOAI nvarchar(30),@MALOAI_TAM INT)
as
	begin
		UPDATE LOAIHANG SET TENLOAI = @TENLOAI WHERE MALOAI = @MALOAI_TAM
	end
go
EXEC SUA_LOAIHANG 'LT004', N'phụ kiện', 'LT004'
go

-- ĐỨNG Ở SA
-- 1. TẠO ADMIN MỚI - DEAN5 
CREATE LOGIN [Ad] WITH PASSWORD = '1';

USE [DEAN5];
CREATE USER [Ad] FOR LOGIN [Ad];
ALTER ROLE db_owner ADD MEMBER [Ad];

-- 2. TẠO NGƯỜI DÙNG - BẰNG THỦ TỤC
CREATE PROC PHANQUYEN_DANGKY  
    @USERNAME NVARCHAR(30), 
    @PASSWORD NVARCHAR(30)
AS
BEGIN
    DECLARE @sql NVARCHAR(MAX);

    -- Tạo Login
    SET @sql = N'CREATE LOGIN [' + @USERNAME + N'] WITH PASSWORD = N''' + @PASSWORD + N''''
    EXEC sp_executesql @sql

    -- Tạo User từ Login
    SET @sql = N'CREATE USER [' + @USERNAME + N'] FOR LOGIN [' + @USERNAME + N']'
    EXEC sp_executesql @sql

    -- Gán quyền làm việc với bảng USERSESSIONS
    SET @sql = N'GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.UserSessions TO [' + @USERNAME + N']'
    EXEC sp_executesql @sql

    -- Gán quyền EXECUTE trên stored procedures cần thiết
    SET @sql = N'GRANT EXECUTE ON OBJECT::dbo.PHANQUYEN_DANGKY TO [' + @USERNAME + N']'
    EXEC sp_executesql @sql
    -- 1. insert
    SET @sql = N'GRANT EXECUTE ON OBJECT::dbo.UserSessions_insert TO [' + @USERNAME + N']'
    EXEC sp_executesql @sql

    -- 2. delete
    SET @sql = N'GRANT EXECUTE ON OBJECT::dbo.DELETE_ALL_USERNAME_IN_USERSESSIONS TO [' + @USERNAME + N']'
    EXEC sp_executesql @sql

    -- 3. select quyền trên function GET_USER_ID
    SET @sql = N'GRANT SELECT ON OBJECT::dbo.GET_USER_ID TO [' + @USERNAME + N']'
    EXEC sp_executesql @sql


	---- 4. select quyền trên procedures DISPLAY_HANGHOA
 --   SET @sql = N'GRANT EXECUTE ON OBJECT::dbo.DISPLAY_HANGHOA TO [' + @USERNAME + N']'
 --   EXEC sp_executesql @sql
	---- 5. quyền lưu hóa đơn
	--SET @sql = N'GRANT EXECUTE ON OBJECT::dbo.P_LUU_HOADON_THANHTOAN TO [' + @USERNAME + N']'
 --   EXEC sp_executesql @sql
	---- 6. quyền lưu chi tiết hóa đơn
	--SET @sql = N'GRANT EXECUTE ON OBJECT::dbo.P_LUU_CHITIETHOADON_THANHTOAN TO [' + @USERNAME + N']'
 --   EXEC sp_executesql @sql
	----7. quyền lấy mã hóa đơn mới nhất
	--SET @sql = N'GRANT SELECT ON OBJECT::dbo.F_MaHD_Moi TO [' + @USERNAME + N']'
 --   EXEC sp_executesql @sql
	----8. quyền tìm manv cho lưu hóa đơn
	--SET @sql = N'GRANT SELECT ON OBJECT::dbo.F_TIM_MANV TO [' + @USERNAME + N']'
 --   EXEC sp_executesql @sql

	-- Thay `SELECT` bằng `EXECUTE` cho hàm F_MaHD_Moi
    SET @sql = N'GRANT EXECUTE ON OBJECT::dbo.F_MaHD_Moi TO [' + @USERNAME + N']';
    EXEC sp_executesql @sql;

 --   -- Thay `SELECT` bằng `EXECUTE` cho hàm F_TIM_MANV
 --   SET @sql = N'GRANT EXECUTE ON OBJECT::dbo.F_TIM_MANV TO [' + @USERNAME + N']';
 --   EXEC sp_executesql @sql;

	-- Quyền xem ca trực
    SET @sql = N'GRANT EXECUTE ON OBJECT::dbo.P_TEN_CA TO [' + @USERNAME + N']';
    EXEC sp_executesql @sql;

	---- Quyền xem số lượng tồn của sản phẩm
 --   SET @sql = N'GRANT EXECUTE ON OBJECT::dbo.P_SL_TONKHO_SP TO [' + @USERNAME + N']';
 --   EXEC sp_executesql @sql;

	---- Quyền thêm một khách hàng nếu có
 --   SET @sql = N'GRANT EXECUTE ON OBJECT::dbo.INSERT_KHACHHANG TO [' + @USERNAME + N']';
 --   EXEC sp_executesql @sql;


END;


EXEC PHANQUYEN_DANGKY 'a', 'a'
------------------------------------------------

-- ĐỨNG Ở ADMIN MỚI (AD) ĐỂ PHÂN QUYỀN CHO USER (DO SA KHÔNG GRANT ĐƯỢC)

SELECT name FROM sys.tables

SELECT name
FROM sys.objects 
WHERE type IN ('U', 'V')

-- Lấy tất cả Stored Procedures
SELECT name 
FROM sys.objects 
WHERE type = 'P';

-- Lấy tất cả Stored Procedures
SELECT name 
FROM sys.objects 
WHERE type IN ('FN', 'IF', 'TF');


SELECT 
    dp.permission_name, 
    dp.state_desc 
FROM 
    sys.database_permissions dp
JOIN 
    sys.database_principals dp2 ON dp.grantee_principal_id = dp2.principal_id
WHERE 
    dp2.name = 'k'
    AND dp.major_id = OBJECT_ID('KHACHHANG');



--kiểm tra các quyền đươc phân bố cho 1 bảng 
SELECT 
    pr.name AS UserName,
    o.name AS ObjectName,
    p.permission_name AS PermissionType
FROM 
    sys.database_permissions p
JOIN 
    sys.objects o ON p.major_id = o.object_id
JOIN 
    sys.database_principals pr ON p.grantee_principal_id = pr.principal_id
WHERE 
    pr.name = '3'  -- Thay 'username' bằng tên người dùng bạn muốn kiểm tra
    AND o.name = 'KHACHHANG'  -- Chỉ kiểm tra quyền trên bảng KHACHHANG
    AND p.permission_name IN ('SELECT', 'INSERT', 'UPDATE', 'DELETE');

--kiểm tra các quyền được phân bố cho một thủ tục
SELECT 
    pr.name AS UserName,
    o.name AS ObjectName,
    p.permission_name AS PermissionType
FROM 
    sys.database_permissions p
JOIN 
    sys.objects o ON p.major_id = o.object_id
JOIN 
    sys.database_principals pr ON p.grantee_principal_id = pr.principal_id
WHERE 
    pr.name = '5'  -- Thay 'username' bằng tên người dùng bạn muốn kiểm tra
    AND p.permission_name = 'EXECUTE'
    AND o.type = 'P';  -- Chỉ kiểm tra trên các thủ tục (loại 'P')

---Thêm cột user name cho bảng nhân viên
ALTER TABLE NHANVIEN
ADD TENDN NVARCHAR(100)

SELECT * FROM NHANVIEN

UPDATE NHANVIEN
SET TENDN='vana'
WHERE MANV=1
---Hàm so sánh lấy mã nhân viên
CREATE FUNCTION F_TIM_MANV(@TENDN NVARCHAR(100))
RETURNS INT
AS
	BEGIN
		DECLARE @MANV INT
		SET @MANV=(SELECT MANV FROM NHANVIEN WHERE TENDN=@TENDN)	
		RETURN @MANV
	END
GO

DECLARE @KQ NVARCHAR(100)
SET @KQ= dbo.F_TIM_MANV('vana')
PRINT @KQ

---Hàm lấy mã hóa đơn mới nhất
CREATE FUNCTION F_MaHD_Moi()
RETURNS INT
AS
	BEGIN
		DECLARE @MaHD INT
		SET @MaHD=(select top(1) MAHD from HOADON ORDER BY MAHD DESC)	
		RETURN @MaHD
	END
GO

DECLARE @KQ NVARCHAR(100)
SET @KQ=select dbo.F_MaHD_Moi()
PRINT @KQ


select * from NHANVIEN
---Thủ tục cấp tài khoản
CREATE PROC P_CAP_TAIKHOAN @MANV INT, @USERNAME NVARCHAR(100)
AS
	BEGIN
		UPDATE NHANVIEN
		SET TENDN=@USERNAME
		WHERE MANV=@MANV
	END
GO

EXEC P_CAP_TAIKHOAN 2, 'thib'

--THỦ TỤC BÁN HÀNG
CREATE PROC [dbo].[P_LUU_HOADON_THANHTOAN] @MAHD CHAR(100), @NGAYLAP DATE, @TRANGTHAI NVARCHAR(100), @MANV INT
AS
	BEGIN
		INSERT INTO HOADON (MAHD,NGAYLAP,TRANGTHAI, MANV) VALUES (@MAHD,@NGAYLAP,@TRANGTHAI,@MANV)
	END

CREATE PROC [dbo].[P_LUU_CHITIETHOADON_THANHTOAN] @MAHD char(100), @MAHG INT, @SL INT, @DONGIA FLOAT
AS
BEGIN
	INSERT INTO CHITIETHOADON(MAHD, MAHG, SOLUONG, GIABAN) VALUES(@MAHD, @MAHG, @SL, @DONGIA)
END
-- THỦ TỤC NHẬP HÀNG
CREATE PROC [dbo].[P_LUU_PHIEUNHAP_THANHTOAN] @MAPN CHAR(100), @NGAYNHAP DATE, @MANCC INT, @MANV INT
AS
BEGIN
	INSERT INTO PHIEUNHAP (MAPN, NGAYNHAP, MANCC, MANV) VALUES (@MAPN, @NGAYNHAP, @MANCC, @MANV)
END

SELECT * FROM CHITIETPN

CREATE PROC [dbo].[P_LUU_CHITIETPN_THANHTOAN] @MAPN CHAR(100), @MAHG INT, @SL INT, @DONGIA FLOAT
AS
BEGIN
	INSERT INTO CHITIETPN(MAPN, MAHG, SOLUONG, GIABAN) VALUES(@MAPN, @MAHG, @SL, @DONGIA)
END
--THỦ TỤC LẤY TÊN NHÂN VIÊN
ALTER PROC P_TEN_NV(@TENDN NVARCHAR(100))
AS
	BEGIN
		SELECT TENNV FROM NHANVIEN WHERE TENDN=@TENDN
	END
GO
EXEC P_TEN_NV 'sa'
--THỦ TỤC LICHCA
--HIỂN THỊ
CREATE PROC P_HIENTHI_LICHCA
AS
	BEGIN
		SELECT * FROM LICHCA
	END
GO
EXEC P_HIENTHI_LICHCA
--THEM
CREATE PROC P_THEM_LICHCA @TENCA NVARCHAR(100), @TGBATDAU TIME, @TGKETTHUC TIME
AS
	BEGIN
		INSERT INTO LICHCA(TENCACAO, THOIGIANBATDAU, THOIGIANKETTHUC) VALUES(@TENCA, @TGBATDAU, @TGKETTHUC)
	END
GO
EXEC P_THEM_LICHCA N'Ca nửa đêm','12:45:00', '5:15:00'
--XÓA
CREATE PROC P_XOA_LICHCA @MACA INT
AS
	BEGIN
		DELETE FROM LICHCA
		WHERE MACA=@MACA
	END
GO
EXEC P_XOA_LICHCA 4
--SỬA
CREATE PROC P_SUA_LICHCA @MACA INT, @TENCA NVARCHAR(100), @TGBATDAU TIME, @TGKETTHUC TIME
AS
	BEGIN
		UPDATE LICHCA
		SET TENCACAO=@TENCA, THOIGIANBATDAU=@TGBATDAU, THOIGIANKETTHUC=@TGKETTHUC
		WHERE MACA=@MACA
	END
GO
EXEC P_SUA_LICHCA 5, N'Ca sắp sáng', '12:45:00', '6:50:00'
--THỦ TỤC LICTRUC
--HIỂN THỊ
CREATE PROC P_HIENTHI_LICTRUC
AS
	BEGIN
		SELECT * FROM LICHTRUC
	END
GO
EXEC P_HIENTHI_LICTRUC
--THÊM
SET DATEFORMAT DMY
CREATE PROC P_THEM_LICTRUC @MANV INT, @MACA INT, @NGAYTRUC DATE
AS
	BEGIN
		INSERT INTO LICHTRUC VALUES(@MANV, @MACA, @NGAYTRUC)
	END
GO
EXEC P_THEM_LICTRUC 1, 1, '12/11/2024'
--XÓA
CREATE PROC P_XOA_LICHTRUC @MANV INT, @MACA INT, @NGAYTRUC DATE
AS
	BEGIN
		DELETE FROM LICHTRUC
		WHERE MANV=@MANV AND MACA=@MACA AND NGAYTRUC=@NGAYTRUC
	END
GO
EXEC P_XOA_LICHTRUC 1, 1, '11/12/2024'
--SỬA
CREATE PROC P_SUA_LICTRUC @MANV INT, @MACA INT, @NGAYTRUC DATE, @MANV_OLD INT, @MACA_OLD INT, @NGAYTRUC_OLD DATE
AS
	BEGIN
		UPDATE LICHTRUC
		SET MANV=@MANV, MACA=@MACA, NGAYTRUC=@NGAYTRUC
		WHERE MANV=@MANV_OLD AND MACA=@MACA_OLD AND NGAYTRUC=@NGAYTRUC_OLD
	END
GO
EXEC P_SUA_LICTRUC 1, 1, '12/11/2024', 1, 1, '13/11/2024'
-- ĐÂY LÀ HÀM ĐỂ LẤY RA TẤT CẢ CÁC THỦ TỤC || HÀM LIÊN QUAN ĐẾN MỘT BẢNG
------------------------
CREATE FUNCTION GET_P_F_FOR_A_TABLE (@TABLE_NAME NVARCHAR(MAX)) 
RETURNS TABLE
AS
    RETURN (
        SELECT TOP 100 PERCENT
            o.name AS ObjectName,
            o.type_desc AS ObjectType,
            s.name AS SchemaName
        FROM 
            sys.objects o
        JOIN 
            sys.schemas s ON o.schema_id = s.schema_id
        JOIN 
            sys.sql_expression_dependencies dep ON dep.referencing_id = o.object_id
        JOIN 
            sys.tables t ON t.object_id = dep.referenced_id
        WHERE 
            t.name = @TABLE_NAME
        ORDER BY 
            o.type_desc, o.name
    );


SELECT * FROM DBO.GET_P_F_FOR_A_TABLE ('NHANVIEN')
CREATE PROC P_ADMIN_PHANQUYEN_USER 
    @USERNAME CHAR(20), 
    @TABLE CHAR(20), 
    @QUYENDUOCCAP NVARCHAR(MAX)
AS
BEGIN
    DECLARE @sqlCommand NVARCHAR(MAX);
    DECLARE @ObjectName NVARCHAR(255);

    -- Thu hồi quyền EXECUTE trên tất cả các thủ tục, hàm liên quan đến bảng trước khi phân quyền mới
    DECLARE db_cursor CURSOR FOR
        SELECT ObjectName
        FROM DBO.GET_P_F_FOR_A_TABLE(@TABLE);

    OPEN db_cursor;
    FETCH NEXT FROM db_cursor INTO @ObjectName;

    WHILE @@FETCH_STATUS = 0
    BEGIN
        -- Thu hồi quyền EXECUTE trên từng thủ tục và hàm
        SET @sqlCommand = N'REVOKE EXECUTE ON OBJECT::dbo.' + QUOTENAME(@ObjectName) + ' FROM ' + QUOTENAME(@USERNAME);
        EXEC sp_executesql @sqlCommand;
        
        FETCH NEXT FROM db_cursor INTO @ObjectName;
    END

    CLOSE db_cursor;
    DEALLOCATE db_cursor;

    -- Phân quyền mới dựa trên quyền được chọn trong @QUYENDUOCCAP
    -- Phân quyền SELECT cho các thủ tục và hàm có liên quan
    IF (@QUYENDUOCCAP LIKE '%SELECT%')
    BEGIN
        DECLARE db_cursor CURSOR FOR
            SELECT ObjectName
            FROM DBO.GET_P_F_FOR_A_TABLE(@TABLE)
            WHERE ObjectName LIKE 'DISPLAY%' OR ObjectName LIKE 'HIENTHI%'  -- Lọc thủ tục DISPLAY và HIENTHI

        OPEN db_cursor;
        FETCH NEXT FROM db_cursor INTO @ObjectName;

        WHILE @@FETCH_STATUS = 0
        BEGIN
            SET @sqlCommand = N'GRANT EXECUTE ON OBJECT::dbo.' + QUOTENAME(@ObjectName) + ' TO ' + QUOTENAME(@USERNAME);
            EXEC sp_executesql @sqlCommand;
            
            FETCH NEXT FROM db_cursor INTO @ObjectName;
        END

        CLOSE db_cursor;
        DEALLOCATE db_cursor;
    END

    -- Phân quyền INSERT cho các thủ tục liên quan
    IF (@QUYENDUOCCAP LIKE '%INSERT%')
    BEGIN
        DECLARE db_cursor CURSOR FOR
            SELECT ObjectName
            FROM DBO.GET_P_F_FOR_A_TABLE(@TABLE)
            WHERE ObjectName LIKE 'INSERT%'  -- Chỉ cấp quyền cho các thủ tục INSERT

        OPEN db_cursor;
        FETCH NEXT FROM db_cursor INTO @ObjectName;

        WHILE @@FETCH_STATUS = 0
        BEGIN
            SET @sqlCommand = N'GRANT EXECUTE ON OBJECT::dbo.' + QUOTENAME(@ObjectName) + ' TO ' + QUOTENAME(@USERNAME);
            EXEC sp_executesql @sqlCommand;
            
            FETCH NEXT FROM db_cursor INTO @ObjectName;
        END

        CLOSE db_cursor;
        DEALLOCATE db_cursor;
    END

    -- Phân quyền DELETE cho các thủ tục liên quan
    IF (@QUYENDUOCCAP LIKE '%DELETE%')
    BEGIN
        DECLARE db_cursor CURSOR FOR
            SELECT ObjectName
            FROM DBO.GET_P_F_FOR_A_TABLE(@TABLE)
            WHERE ObjectName LIKE 'DELETE%'  -- Chỉ cấp quyền cho các thủ tục DELETE

        OPEN db_cursor;
        FETCH NEXT FROM db_cursor INTO @ObjectName;

        WHILE @@FETCH_STATUS = 0
        BEGIN
SET @sqlCommand = N'GRANT EXECUTE ON OBJECT::dbo.' + QUOTENAME(@ObjectName) + ' TO ' + QUOTENAME(@USERNAME);
            EXEC sp_executesql @sqlCommand;
            
            FETCH NEXT FROM db_cursor INTO @ObjectName;
        END

        CLOSE db_cursor;
        DEALLOCATE db_cursor;
    END

    -- Phân quyền UPDATE cho các thủ tục liên quan
    IF (@QUYENDUOCCAP LIKE '%UPDATE%')
    BEGIN
        DECLARE db_cursor CURSOR FOR
            SELECT ObjectName
            FROM DBO.GET_P_F_FOR_A_TABLE(@TABLE)
            WHERE ObjectName LIKE 'UPDATE%'  -- Chỉ cấp quyền cho các thủ tục UPDATE

        OPEN db_cursor;
        FETCH NEXT FROM db_cursor INTO @ObjectName;

        WHILE @@FETCH_STATUS = 0
        BEGIN
            SET @sqlCommand = N'GRANT EXECUTE ON OBJECT::dbo.' + QUOTENAME(@ObjectName) + ' TO ' + QUOTENAME(@USERNAME);
            EXEC sp_executesql @sqlCommand;
            
            FETCH NEXT FROM db_cursor INTO @ObjectName;
        END

        CLOSE db_cursor;
        DEALLOCATE db_cursor;
    END
END




SELECT 
u.name AS UserName,
s.name AS SchemaName,
p.name AS ProcedureName,
f.name AS FunctionName,
t.name AS TableName
FROM 
    sys.procedures p
JOIN 
    sys.schemas s ON p.schema_id = s.schema_id
JOIN 
    sys.database_permissions perm ON perm.major_id = p.object_id
JOIN 
    sys.sysusers u ON u.uid = perm.grantee_principal_id
JOIN 
    sys.sql_expression_dependencies dep ON dep.referencing_id = p.object_id
JOIN 
    sys.tables t ON t.object_id = dep.referenced_id
LEFT JOIN 
    sys.objects f ON f.object_id = dep.referenced_id AND f.type IN ('FN', 'IF', 'TF')
WHERE 
    perm.permission_name = 'EXECUTE'
    --AND u.name = 'a'
	AND t.name = 'HANGHOA'
ORDER BY 
    UserName, SchemaName, ProcedureName, FunctionName, TableName;
--THỦ TỤC CHAMCONG
--HIỂN THỊ
CREATE PROC P_HIENTHI_CHAMCONG
AS
	BEGIN
		SELECT * FROM CHAMCONG
	END
GO
EXEC P_HIENTHI_CHAMCONG
--THÊM
CREATE PROC P_THEM_CHAMCONG @MANV INT, @MACA INT, @NGAYLAM DATE, @TGVAO TIME, @TGRA TIME, @GHICHU NVARCHAR(100)
AS
	BEGIN
		INSERT INTO CHAMCONG(MANV, MACA, NGAYLAM, THOIGIANVAO, THOIGIANRA, GHICHU) VALUES(@MANV, @MACA, @NGAYLAM, @TGVAO, @TGRA, @GHICHU)
	END
GO
EXEC P_THEM_CHAMCONG 1, 2, '13/11/2024','12:00', '18:30',N''

--XÓA
CREATE PROC P_XOA_CHAMCONG @MANV INT, @MACA INT, @NGAYLAM DATE
AS
	BEGIN
		DELETE FROM CHAMCONG
		WHERE MANV=@MANV AND MACA=@MACA AND NGAYLAM = @NGAYLAM
	END
GO
EXEC P_XOA_CHAMCONG 1, 2, '13/11/2024'
--SỬA
CREATE PROC P_SUA_CHAMCONG @MANV INT, @MACA INT, @NGAYLAM DATE, @TGVAO TIME, @TGRA TIME, @GHICHU NVARCHAR(100), @MANV_OLD INT, @MACA_OLD INT, @NGAYLAM_OLD DATE
AS
	BEGIN
		UPDATE CHAMCONG
		SET MANV=@MANV, MACA=@MACA, NGAYLAM=@NGAYLAM, THOIGIANVAO=@TGVAO, THOIGIANRA=@TGRA, GHICHU=@GHICHU
		WHERE MANV=@MANV_OLD AND MACA=@MACA_OLD AND NGAYLAM = @NGAYLAM_OLD
	END
GO
EXEC P_SUA_CHAMCONG 1, 1, '12/11/2024','8:00','11:30',N'', 1, 1, '12/11/2024'
--THỦ TỤC TÍNH LƯƠNG
SELECT NHANVIEN.MANV, TENNV, SUM(DATEDIFF(HOUR, THOIGIANVAO, THOIGIANRA)) AS SoGioLam, (SUM(DATEDIFF(HOUR, THOIGIANVAO, THOIGIANRA)) * 20000) AS TongLuong
                    FROM ChamCong , NHANVIEN, LICHTRUC
                    WHERE (CHAMCONG.MANV=LICHTRUC.MANV AND CHAMCONG.MACA=LICHTRUC.MACA AND CHAMCONG.NGAYLAM=LICHTRUC.NGAYTRUC)
                    AND LICHTRUC.MANV=NHANVIEN.MANV
                    AND (DAY(NGAYLAM) = ''  AND MONTH(NGAYLAM) = 11 AND YEAR(NGAYLAM) = 2024)
					GROUP BY NHANVIEN.MANV, TENNV

--THỦ TỤC TÊN CA
CREATE PROC P_TEN_CA(@TENDN NVARCHAR(100))
AS 
	BEGIN
		SELECT TENCACAO
		FROM LICHTRUC, LICHCA
		WHERE MANV=(SELECT MANV FROM NHANVIEN WHERE TENDN=@TENDN) AND NGAYTRUC=CAST(GETDATE() AS DATE) and LICHTRUC.MACA=LICHCA.MACA
	END
GO
EXEC P_TEN_CA 1

SELECT * FROM NHANVIEN


-- THỦ TỤC LẤY QUYỀN THEO USER
CREATE PROC P_GET_PERMISSION_FOR_USER @USERNAME NVARCHAR(100)
AS
BEGIN
	SELECT 
	u.name AS UserName,
	--s.name AS SchemaName,
	p.name AS ProcedureName,
	f.name AS FunctionName,
	t.name AS TableName
	FROM 
		sys.procedures p
	JOIN 
		sys.schemas s ON p.schema_id = s.schema_id
	JOIN 
		sys.database_permissions perm ON perm.major_id = p.object_id
	JOIN 
		sys.sysusers u ON u.uid = perm.grantee_principal_id
	JOIN 
		sys.sql_expression_dependencies dep ON dep.referencing_id = p.object_id
	JOIN 
		sys.tables t ON t.object_id = dep.referenced_id
	LEFT JOIN 
		sys.objects f ON f.object_id = dep.referenced_id AND f.type IN ('FN', 'IF', 'TF')
	WHERE 
		perm.permission_name = 'EXECUTE'
		AND u.name = @USERNAME
	ORDER BY 
		--UserName, SchemaName, ProcedureName, FunctionName, TableName;
		UserName, ProcedureName, FunctionName, TableName;

END

EXEC P_GET_PERMISSION_FOR_USER '2'
-- BẮT ĐẦU LÀM PHÂN QUYỀN LẠI Ở ĐÂY
-- ĐẦU TIÊN LÀ PHÂN QUYỀN:
-- TẠO BẢNG PHÂN QUYỀN:
CREATE TABLE PhanQuyen (
    MaQuyen INT PRIMARY KEY IDENTITY(1,1),
    MoTa NVARCHAR(MAX) NOT NULL,         -- Mô tả quyền
    CauLenhSQL_PhanQuyen NVARCHAR(MAX) NOT NULL,
    CauLenhSQL_ThuHoiQuyen NVARCHAR(MAX) NOT NULL
);

DROP TABLE PhanQuyen
DELETE FROM PhanQuyen
-- Lệnh INSERT cho các thủ tục
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Lưu hóa đơn thanh toán', 'GRANT EXECUTE ON OBJECT::dbo.P_LUU_HOADON_THANHTOAN TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.P_LUU_HOADON_THANHTOAN FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Xem hàng chưa bán', 'GRANT EXECUTE ON OBJECT::dbo.HANG_CHUA_BAN TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.HANG_CHUA_BAN FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Thanh toán - lưu chi tiết hóa đơn', 'GRANT EXECUTE ON OBJECT::dbo.P_LUU_CHITIETHOADON_THANHTOAN TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.P_LUU_CHITIETHOADON_THANHTOAN FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Xem hàng bán chạy nhất', 'GRANT EXECUTE ON OBJECT::dbo.HANG_BAN_CHAY_NHAT TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.HANG_BAN_CHAY_NHAT FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Thanh toán - lưu phiếu nhập', 'GRANT EXECUTE ON OBJECT::dbo.P_LUU_PHIEUNHAP_THANHTOAN TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.P_LUU_PHIEUNHAP_THANHTOAN FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Xem hàng chưa bán và tổng', 'GRANT EXECUTE ON OBJECT::dbo.HANG_CHUA_BAN_VA_TONG TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.HANG_CHUA_BAN_VA_TONG FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Thanh toán - lưu chi tiết phiếu nhập', 'GRANT EXECUTE ON OBJECT::dbo.P_LUU_CHITIETPN_THANHTOAN TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.P_LUU_CHITIETPN_THANHTOAN FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Kiểm tra hàng tồn kho', 'GRANT EXECUTE ON OBJECT::dbo.P_KIEMTRA_TONKHO TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.P_KIEMTRA_TONKHO FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Xem bảng khách hàng', 'GRANT EXECUTE ON OBJECT::dbo.DISPLAY_KHACHHANG TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.DISPLAY_KHACHHANG FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Thêm bảng khách hàng', 'GRANT EXECUTE ON OBJECT::dbo.INSERT_KHACHHANG TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.INSERT_KHACHHANG FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Xóa bảng khách hàng', 'GRANT EXECUTE ON OBJECT::dbo.DELETE_KHACHHANG TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.DELETE_KHACHHANG FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Sửa bảng khách hàng', 'GRANT EXECUTE ON OBJECT::dbo.UPDATE_KHACHHANG TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.UPDATE_KHACHHANG FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Xem tên nhân viên', 'GRANT EXECUTE ON OBJECT::dbo.P_TEN_NV TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.P_TEN_NV FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Hiển thị hóa đơn (view)', 'GRANT EXECUTE ON OBJECT::dbo.DISPLAY_HOADON_VIEW TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.DISPLAY_HOADON_VIEW FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Thêm hóa đơn (view)', 'GRANT EXECUTE ON OBJECT::dbo.INSERT_HOADON_VIEW TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.INSERT_HOADON_VIEW FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Xóa hóa đơn (view)', 'GRANT EXECUTE ON OBJECT::dbo.DELETE_HOADON_VIEW TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.DELETE_HOADON_VIEW FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Cấp tài khoản', 'GRANT EXECUTE ON OBJECT::dbo.P_CAP_TAIKHOAN TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.P_CAP_TAIKHOAN FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Sửa hóa đơn (view)', 'GRANT EXECUTE ON OBJECT::dbo.UPDATE_HOADON_VIEW TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.UPDATE_HOADON_VIEW FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Hiển thị nhân viên (view)', 'GRANT EXECUTE ON OBJECT::dbo.DISPLAY_NHANVIEN_VIEW TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.DISPLAY_NHANVIEN_VIEW FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Thêm nhân viên (view)', 'GRANT EXECUTE ON OBJECT::dbo.INSERT_NHANVIEN_VIEW TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.INSERT_NHANVIEN_VIEW FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Xóa nhân viên (view)', 'GRANT EXECUTE ON OBJECT::dbo.DELETE_NHANVIEN_VIEW TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.DELETE_NHANVIEN_VIEW FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Sửa nhân viên (view)', 'GRANT EXECUTE ON OBJECT::dbo.UPDATE_NHANVIEN_VIEW TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.UPDATE_NHANVIEN_VIEW FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Hiển thị hàng hóa', 'GRANT EXECUTE ON OBJECT::dbo.DISPLAY_HANGHOA TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.DISPLAY_HANGHOA FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Thêm hàng hóa', 'GRANT EXECUTE ON OBJECT::dbo.INSERT_HANGHOA TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.INSERT_HANGHOA FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Xóa hàng hóa', 'GRANT EXECUTE ON OBJECT::dbo.DELETE_HANGHOA TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.DELETE_HANGHOA FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Sửa hàng hóa', 'GRANT EXECUTE ON OBJECT::dbo.UPDATE_HANGHOA TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.UPDATE_HANGHOA FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Hiển thị hóa đơn', 'GRANT EXECUTE ON OBJECT::dbo.HIENTHI_HOADON TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.HIENTHI_HOADON FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Thêm hóa đơn', 'GRANT EXECUTE ON OBJECT::dbo.THEM_HOADON TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.THEM_HOADON FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Xóa hóa đơn', 'GRANT EXECUTE ON OBJECT::dbo.XOA_HOADON TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.XOA_HOADON FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Sửa hóa đơn', 'GRANT EXECUTE ON OBJECT::dbo.SUA_HOADON TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.SUA_HOADON FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Hiển thị nhân viên', 'GRANT EXECUTE ON OBJECT::dbo.HIENTHI_NHANVIEN TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.HIENTHI_NHANVIEN FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Thêm nhân viên', 'GRANT EXECUTE ON OBJECT::dbo.THEM_NHANVIEN TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.THEM_NHANVIEN FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Sửa nhân viên', 'GRANT EXECUTE ON OBJECT::dbo.SUA_NHANVIEN TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.SUA_NHANVIEN FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Hiển thị khách hàng (view)', 'GRANT EXECUTE ON OBJECT::dbo.HIENTHI_KHACHHANG_VIEW TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.HIENTHI_KHACHHANG_VIEW FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Thêm khách hàng (view)', 'GRANT EXECUTE ON OBJECT::dbo.THEM_KHACH_VIEW TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.THEM_KHACH_VIEW FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Xóa khách hàng (view)', 'GRANT EXECUTE ON OBJECT::dbo.XOA_KHACH_VIEW TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.XOA_KHACH_VIEW FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Sửa khách hàng (view)', 'GRANT EXECUTE ON OBJECT::dbo.SUA_KHACHHANG_VIEW TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.SUA_KHACHHANG_VIEW FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Hiển thị hàng hóa', 'GRANT EXECUTE ON OBJECT::dbo.HIENTHI_HANGHOA TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.HIENTHI_HANGHOA FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Thêm hàng hóa (THEMHANGHOC)', 'GRANT EXECUTE ON OBJECT::dbo.THEM_HANGHOC TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.THEM_HANGHOC FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Thêm hàng hóa (THEMHANGHOA)', 'GRANT EXECUTE ON OBJECT::dbo.THEM_HANGHOA TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.THEM_HANGHOA FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Xóa hàng hóa', 'GRANT EXECUTE ON OBJECT::dbo.XOA_HANGHOA TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.XOA_HANGHOA FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Sửa hàng hóa', 'GRANT EXECUTE ON OBJECT::dbo.SUA_HANGHOA TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.SUA_HANGHOA FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'UserSessions_insert', 'GRANT EXECUTE ON OBJECT::dbo.UserSessions_insert TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.UserSessions_insert FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Hiển thị chi tiết hóa đơn', 'GRANT EXECUTE ON OBJECT::dbo.HIENTHI_CHITIETHOADON TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.HIENTHI_CHITIETHOADON FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Thêm chi tiết hóa đơn', 'GRANT EXECUTE ON OBJECT::dbo.THEM_CHITIETHOADON TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.THEM_CHITIETHOADON FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Xóa chi tiết hóa đơn', 'GRANT EXECUTE ON OBJECT::dbo.XOA_CHITIETHOADON TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.XOA_CHITIETHOADON FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Sửa chi tiết hóa đơn', 'GRANT EXECUTE ON OBJECT::dbo.SUA_CHITIETHOADON TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.SUA_CHITIETHOADON FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'DELETE_ALL_USERNAME_IN_USERSESSIONS', 'GRANT EXECUTE ON OBJECT::dbo.DELETE_ALL_USERNAME_IN_USERSESSIONS TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.DELETE_ALL_USERNAME_IN_USERSESSIONS FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'EXPORT_FROM_ANY_TABLE', 'GRANT EXECUTE ON OBJECT::dbo.EXPORT_FROM_ANY_TABLE TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.EXPORT_FROM_ANY_TABLE FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Hiển thị thông tin nhân viên', 'GRANT EXECUTE ON OBJECT::dbo.DISPLAY_THONGTINNHANVIEN TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.DISPLAY_THONGTINNHANVIEN FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Thêm thông tin nhân viên', 'GRANT EXECUTE ON OBJECT::dbo.INSERT_THONGTINNHANVIEN TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.INSERT_THONGTINNHANVIEN FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Xóa thông tin nhân viên', 'GRANT EXECUTE ON OBJECT::dbo.DELETE_THONGTINNHANVIEN TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.DELETE_THONGTINNHANVIEN FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Sửa thông tin nhân viên', 'GRANT EXECUTE ON OBJECT::dbo.UPDATE_THONGTINNHANVIEN TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.UPDATE_THONGTINNHANVIEN FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Thêm chi tiết phiếu nhập', 'GRANT EXECUTE ON OBJECT::dbo.THEM_CHITIETPN TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.THEM_CHITIETPN FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Xóa chi tiết phiếu nhập', 'GRANT EXECUTE ON OBJECT::dbo.XOA_CHITIETPN TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.XOA_CHITIETPN FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Sửa chi tiết phiếu nhập', 'GRANT EXECUTE ON OBJECT::dbo.SUA_CHITIETPN TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.SUA_CHITIETPN FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Thêm phiếu nhập', 'GRANT EXECUTE ON OBJECT::dbo.THEM_PHIEUNHAP TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.THEM_PHIEUNHAP FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Xóa phiếu nhập', 'GRANT EXECUTE ON OBJECT::dbo.XOA_PHIEUNHAP TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.XOA_PHIEUNHAP FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Sửa phiếu nhập', 'GRANT EXECUTE ON OBJECT::dbo.SUA_PHIEUNHAP TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.SUA_PHIEUNHAP FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Thêm nhà cung cấp', 'GRANT EXECUTE ON OBJECT::dbo.THEM_NHACC TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.THEM_NHACC FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Xóa nhà cung cấp', 'GRANT EXECUTE ON OBJECT::dbo.XOA_NHACC TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.XOA_NHACC FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Sửa nhà cung cấp', 'GRANT EXECUTE ON OBJECT::dbo.SUA_NHACC TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.SUA_NHACC FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Thêm loại hàng', 'GRANT EXECUTE ON OBJECT::dbo.THEM_LOAIHANG TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.THEM_LOAIHANG FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Xóa loại hàng', 'GRANT EXECUTE ON OBJECT::dbo.XOA_LOAIHANG TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.XOA_LOAIHANG FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Sửa loại hàng', 'GRANT EXECUTE ON OBJECT::dbo.SUA_LOAIHANG TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.SUA_LOAIHANG FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'PHANQUYEN_DANGKY', 'GRANT EXECUTE ON OBJECT::dbo.PHANQUYEN_DANGKY TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.PHANQUYEN_DANGKY FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'P_ADMIN_PHANQUYEN_USER', 'GRANT EXECUTE ON OBJECT::dbo.P_ADMIN_PHANQUYEN_USER TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.P_ADMIN_PHANQUYEN_USER FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Lấy loại (hạng) của khách hàng', 'GRANT EXECUTE ON OBJECT::dbo.P_GETLOAIKH TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.P_GETLOAIKH FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Xuất loại (hạng) của khách hàng', 'GRANT EXECUTE ON OBJECT::dbo.P_XUAT_HANG_KHACH_HANG TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.P_XUAT_HANG_KHACH_HANG FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Hiển thị chi tiết khuyến mãi', 'GRANT EXECUTE ON OBJECT::dbo.DISPLAY_CHITIETKHUYENMAI TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.DISPLAY_CHITIETKHUYENMAI FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Thêm chi tiết khuyến mãi', 'GRANT EXECUTE ON OBJECT::dbo.INSERT_CHITIETKHUYENMAI TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.INSERT_CHITIETKHUYENMAI FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Xóa chi tiết khuyến mãi', 'GRANT EXECUTE ON OBJECT::dbo.DELETE_CHITIETKHUYENMAI TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.DELETE_CHITIETKHUYENMAI FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Sửa chi tiết khuyến mãi', 'GRANT EXECUTE ON OBJECT::dbo.UPDATE_CHITIETKHUYENMAI TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.UPDATE_CHITIETKHUYENMAI FROM @username');


INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Hiển thị lịch ca', 'GRANT EXECUTE ON OBJECT::dbo.P_HIENTHI_LICHCA TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.UPDATE_CHITIETKHUYENMAI FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Thêm lịch ca', 'GRANT EXECUTE ON OBJECT::dbo.P_THEM_LICHCA TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.UPDATE_CHITIETKHUYENMAI FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Xóa lịch ca', 'GRANT EXECUTE ON OBJECT::dbo.P_XOA_LICHCA TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.UPDATE_CHITIETKHUYENMAI FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Sửa lịch ca', 'GRANT EXECUTE ON OBJECT::dbo.P_SUA_LICHCA TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.UPDATE_CHITIETKHUYENMAI FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Hiển thị lịch trực', 'GRANT EXECUTE ON OBJECT::dbo.P_HIENTHI_LICTRUC TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.UPDATE_CHITIETKHUYENMAI FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Thêm lịch trực', 'GRANT EXECUTE ON OBJECT::dbo.P_THEM_LICTRUC TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.UPDATE_CHITIETKHUYENMAI FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Xóa lịch trực', 'GRANT EXECUTE ON OBJECT::dbo.P_XOA_LICHTRUC TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.UPDATE_CHITIETKHUYENMAI FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Sửa lịch trực', 'GRANT EXECUTE ON OBJECT::dbo.P_SUA_LICTRUC TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.UPDATE_CHITIETKHUYENMAI FROM @username');

INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Xem ca trực', 'GRANT EXECUTE ON OBJECT::dbo.P_TEN_CA TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.P_TEN_CA FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Hiển thị chấm công', 'GRANT EXECUTE ON OBJECT::dbo.P_HIENTHI_CHAMCONG TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.P_HIENTHI_CHAMCONG FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Thêm chấm công', 'GRANT EXECUTE ON OBJECT::dbo.P_THEM_CHAMCONG TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.P_THEM_CHAMCONG FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Xóa chấm công', 'GRANT EXECUTE ON OBJECT::dbo.P_XOA_CHAMCONG TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.P_XOA_CHAMCONG FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'Sửa chấm công', 'GRANT EXECUTE ON OBJECT::dbo.P_SUA_CHAMCONG TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.P_SUA_CHAMCONG FROM @username');


-- Lệnh INSERT cho các hàm
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'(Hàm) Tìm mã nhân viên', 'GRANT EXECUTE ON OBJECT::dbo.F_TIM_MANV TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.F_TIM_MANV FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'(Hàm) Lấy mã hóa đơn mới nhất ', 'GRANT EXECUTE ON OBJECT::dbo.F_MaHD_Moi TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.F_MaHD_Moi FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'(Hàm) Lấy ra tất cả thủ tục hoặc hàm của một bảng cụ thể', 'GRANT SELECT ON OBJECT::dbo.GET_P_F_FOR_A_TABLE TO @username', 'REVOKE SELECT ON OBJECT::dbo.GET_P_F_FOR_A_TABLE FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'(Hàm) Lấy ra các user đã đăng nhập', 'GRANT SELECT ON OBJECT::dbo.GET_USER_ID TO @username', 'REVOKE SELECT ON OBJECT::dbo.GET_USER_ID FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'(Hàm) Hiển thị chi tiết phiếu nhập', 'GRANT SELECT ON OBJECT::dbo.F_HIENTHI_CHITIETPN TO @username', 'REVOKE SELECT ON OBJECT::dbo.F_HIENTHI_CHITIETPN FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'(Hàm) Hiển thị phiếu nhập', 'GRANT SELECT ON OBJECT::dbo.F_HIENTHI_PHIEUNHAP TO @username', 'REVOKE SELECT ON OBJECT::dbo.F_HIENTHI_PHIEUNHAP FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'(Hàm) Hiển thị nhà cung cấp', 'GRANT SELECT ON OBJECT::dbo.F_HIENTHI_NHACC TO @username', 'REVOKE SELECT ON OBJECT::dbo.F_HIENTHI_NHACC FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'(Hàm) Hiển thị loại hàng', 'GRANT SELECT ON OBJECT::dbo.F_HIENTHI_LOAIHANG TO @username', 'REVOKE SELECT ON OBJECT::dbo.F_HIENTHI_LOAIHANG FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'(Hàm) Tính tuổi nhân viên', 'GRANT EXECUTE ON OBJECT::dbo.F_TinhTuoiNhanVien TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.F_TinhTuoiNhanVien FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'(Hàm) Giảm giá', 'GRANT EXECUTE ON OBJECT::dbo.F_GIAMGIA TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.F_GIAMGIA FROM @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'(Hàm) Kiểm tra sự tồn tại của khách hàng', 'GRANT EXECUTE ON OBJECT::dbo.F_KIEMTRA_TONTAI_KH TO @username', 'REVOKE EXECUTE ON OBJECT::dbo.F_KIEMTRA_TONTAI_KH FROM @username');

--Lệnh insert nhóm quyền
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'(Nhóm quyền) Bán hàng', 'sp_addrolemember BanHang, @username', 'sp_droprolemember BanHang, @username');
INSERT INTO PhanQuyen (MoTa, CauLenhSQL_PhanQuyen, CauLenhSQL_ThuHoiQuyen) VALUES (N'(Nhóm quyền) Nhập hàng', 'sp_addrolemember NhapHang, @username', 'sp_droprolemember NhapHang, @username');


-- TẠO THỦ TỤC ĐỂ GỌI BẢNG PHÂN QUYỀN
CREATE PROC P_PHANQUYEN 
AS
BEGIN
	SELECT * FROM PhanQuyen
END

-- TẠO THỦ TỤC ĐỂ LẤY RA CÂU LỆNH PHÂN QUYỀN
CREATE PROC P_PHANQUYEN_FOR_USER @MAQUYEN INT
AS
BEGIN
	SELECT CauLenhSQL_PhanQuyen
	FROM PhanQuyen
	WHERE MaQuyen = @MAQUYEN
END

EXEC P_PHANQUYEN_FOR_USER 1
-- TẠO THỦ TỤC ĐỂ LẤY RA CÂU LỆNH THU HỒI QUYỀN
CREATE PROC P_THUHOIQUYEN_FOR_USER @MAQUYEN INT
AS
BEGIN
	SELECT CauLenhSQL_ThuHoiQuyen
	FROM PhanQuyen
	WHERE MaQuyen = @MAQUYEN
END

EXEC P_THUHOIQUYEN_FOR_USER 1




EXEC P_PHANQUYEN
--THỦ TỤC TÍNH LƯƠNG
CREATE PROC P_TINH_LUONG @DAY INT, @MONTH INT, @YEAR INT
AS
	BEGIN
		SELECT NHANVIEN.MANV, TENNV, SUM(DATEDIFF(HOUR, THOIGIANVAO, THOIGIANRA)) AS SoGioLam, (SUM(DATEDIFF(HOUR, THOIGIANVAO, THOIGIANRA)) * 20000) AS TongLuong
                    FROM ChamCong , NHANVIEN, LICHTRUC
                    WHERE (CHAMCONG.MANV=LICHTRUC.MANV AND CHAMCONG.MACA=LICHTRUC.MACA AND CHAMCONG.NGAYLAM=LICHTRUC.NGAYTRUC)
                    AND LICHTRUC.MANV=NHANVIEN.MANV
                    AND (DAY(NGAYLAM) = @DAY  AND MONTH(NGAYLAM) = @MONTH AND YEAR(NGAYLAM) = @YEAR)
					GROUP BY NHANVIEN.MANV, TENNV
	END
GO
EXEC P_TINH_LUONG 12,11,2024
--SỐ LƯỢNG TỒN KHO CỦA MỘT SẢN PHẨM BẤT KÌ
CREATE PROC P_SL_TONKHO_SP (@MAHG INT)
AS
BEGIN
    SELECT 
        ISNULL((SELECT SUM(SOLUONG) FROM CHITIETPN WHERE MAHG = @MAHG), 0) - 
        ISNULL((SELECT SUM(SOLUONG) FROM CHITIETHOADON WHERE MAHG = @MAHG), 0) AS SL_TONKHO
END
EXEC P_SL_TONKHO_SP 1
--THỦ TỤC ÁP DỤNG GIẢM GIÁ
CREATE FUNCTION F_GIAMGIA(@TONGTIEN FLOAT)
RETURNS FLOAT
AS
	BEGIN
		DECLARE @GIAMGIA FLOAT
		IF(@TONGTIEN>300000)
			SET @GIAMGIA = @TONGTIEN*0.3
		ELSE IF(@TONGTIEN>250000)
			SET @GIAMGIA = @TONGTIEN*0.25
		ELSE IF(@TONGTIEN>200000)
			SET @GIAMGIA = @TONGTIEN*0.2
		ELSE IF(@TONGTIEN>150000)
			SET @GIAMGIA = @TONGTIEN*0.15
		ELSE IF (@TONGTIEN>100000)
			SET @GIAMGIA = @TONGTIEN*0.1
		ELSE 
			SET @GIAMGIA = 0
		RETURN @GIAMGIA
	END
GO

declare @giamgia float
set @giamgia=dbo.F_GIAMGIA(125000)
print @giamgia
--HÀM KIỂM TRA TỒN TẠI KHÁCH HÀNG
CREATE FUNCTION F_KIEMTRA_TONTAI_KH(@SODT NVARCHAR(100))
RETURNS INT
AS
	BEGIN
		DECLARE @KQ INT
		IF EXISTS(SELECT * FROM KHACHHANG WHERE SODT=@SODT)
			SET @KQ=1
		ELSE
			SET @KQ=0
		RETURN @KQ
	END
GO
SELECT DBO.F_KIEMTRA_TONTAI_KH('0971235123 ')
SELECT * FROM KHACHHANG

--Nhóm quyền
--Bán hàng
GO
sp_addrole BanHang
GRANT EXECUTE ON OBJECT::dbo.DISPLAY_HANGHOA TO BanHang
GRANT EXECUTE ON OBJECT::dbo.P_LUU_HOADON_THANHTOAN TO BanHang
GRANT EXECUTE ON OBJECT::dbo.P_LUU_CHITIETHOADON_THANHTOAN TO BanHang
GRANT EXECUTE ON OBJECT::dbo.F_TIM_MANV TO BanHang
GRANT EXECUTE ON OBJECT::dbo.P_SL_TONKHO_SP TO BanHang
GRANT EXECUTE ON OBJECT::dbo.INSERT_KHACHHANG TO BanHang
GRANT EXECUTE ON OBJECT::dbo.F_GIAMGIA TO BanHang
GRANT EXECUTE ON OBJECT::dbo.HIENTHI_HOADON TO BanHang

--Nhập hàng
GO
sp_addrole NhapHang
GRANT EXECUTE ON OBJECT::dbo.DISPLAY_HANGHOA TO NhapHang
GRANT SELECT ON OBJECT::dbo.F_HIENTHI_PHIEUNHAP TO NhapHang
GRANT SELECT ON OBJECT::dbo.F_HIENTHI_NHACC TO NhapHang
GRANT EXECUTE ON OBJECT::dbo.P_LUU_PHIEUNHAP_THANHTOAN TO NhapHang
GRANT EXECUTE ON OBJECT::dbo.P_LUU_CHITIETPN_THANHTOAN TO NhapHang

/*Thủ tục có tham số*/
CREATE PROC HANG_CHUA_BAN_VA_TONG
    @TongSoLuongChuaBan INT OUTPUT
AS
BEGIN
    SELECT HANGHOA.MAHG, HANGHOA.TENHANG, DVT, MALOAI, TONG_NHAP.TONG_NHAP
    FROM HANGHOA
    JOIN TONG_NHAP ON HANGHOA.MAHG = TONG_NHAP.MAHG
    WHERE NOT EXISTS (
        SELECT * 
        FROM CHITIETHOADON
        WHERE CHITIETHOADON.MAHG = HANGHOA.MAHG
    );
    
    -- Tính tổng số lượng hàng chưa bán
    SELECT @TongSoLuongChuaBan = SUM(TONG_NHAP.TONG_NHAP)
    FROM HANGHOA
    JOIN TONG_NHAP ON HANGHOA.MAHG = TONG_NHAP.MAHG
    WHERE NOT EXISTS (
        SELECT * 
        FROM CHITIETHOADON
        WHERE CHITIETHOADON.MAHG = HANGHOA.MAHG
    );
END
GO
/*Thủ tục sử dụng cấu trúc rẽ nhánh, cấu trúc lặp hoặc các hàm có sẵn*/
CREATE PROCEDURE P_GETLOAIKH
    @ma_khach CHAR(15),
    @tong_chi_tieu FLOAT OUTPUT,
	@rank NVARCHAR(MAX) OUTPUT
AS
BEGIN
    SET @tong_chi_tieu = 0;

    -- Kiểm tra xem khách hàn	g có tồn tại hay không
    IF EXISTS (SELECT 1 FROM KHACHHANG WHERE MAKH = @ma_khach)
    BEGIN
        -- Tính tổng số tiền từ các hóa đơn của khách hàng
        SET @tong_chi_tieu = (
            SELECT SUM(SOLUONG * GIABAN)
            FROM CHITIETHOADON CT
            JOIN HOADON HD ON CT.MAHD = HD.MAHD
            WHERE HD.MAKH = @ma_khach
        );
        -- Nếu khách hàng không có giao dịch nào thì tổng chi tiêu vẫn là 0
        IF @tong_chi_tieu IS NULL
            SET @tong_chi_tieu = 0;

        -- Cập nhật trạng thái thành viên dựa trên tổng chi tiêu
        IF @tong_chi_tieu >= 20000000
        BEGIN
            SET @rank = N'Khách hàng đã được nâng cấp lên thành viên kim cương.';
        END
		ELSE IF @tong_chi_tieu >= 10000000
        BEGIN
            SET @rank = N'Khách hàng đã được nâng cấp lên thành viên vàng.';
        END
		ELSE IF @tong_chi_tieu >= 5000000
        BEGIN
            SET @rank = N'Khách hàng đã được nâng cấp lên thành viên bạc.';
        END
        ELSE IF @tong_chi_tieu >= 2000000
        BEGIN
           SET @rank = N'Khách hàng đã được nâng cấp lên thành viên đồng.';
        END
		ELSE
		BEGIN
           SET @rank = N'Khách hàng thường.';
        END

    END
    ELSE
    BEGIN
         Print N'Không tìm thấy khách hàng với mã đã cung cấp.';
    END
END;

GO
DECLARE @TONGTIEN FLOAT, @RANK NVARCHAR(100), @TAM NVARCHAR(100)
EXEC P_GETLOAIKH 'KH002', @TONGTIEN OUTPUT, @RANK OUTPUT
PRINT N'Khách hàng đã chi tiêu tổng: '+CONVERT(NVARCHAR(30),CONVERT(numeric(16,0), CAST(@TONGTIEN AS FLOAT)))+' '+@RANK
/*Hàm  sử dung, cấu trúc lặp hoặc các hàm có sẵn*/
go
CREATE FUNCTION F_TinhTuoiNhanVien (@MaNV CHAR(15))
RETURNS INT
AS
BEGIN
    DECLARE @NgaySinh DATE;
    SELECT @NgaySinh = NGAYSINH FROM THONGTINNHANVIEN WHERE MANV = @MaNV;    
    RETURN DATEDIFF(YEAR, @NgaySinh, GETDATE());
END;
GO

DECLARE @TUOI INT
SET @TUOI=dbo.F_TinhTuoiNhanVien('NV001')
PRINT @TUOI

DECLARE @TUOI INT
SET @TUOI=dbo.F_TinhTuoiNhanVien('NV001          ')
PRINT @TUOI



select * from NHANVIEN
select * from THONGTINNHANVIEN
GO

--TẠO CURSOR LỘC RANK NGƯỜI DÙNG
go
CREATE PROCEDURE P_XUAT_HANG_KHACH_HANG
AS
BEGIN
    DECLARE @ma_khach CHAR(15);
    DECLARE @ten_khach NVARCHAR(50);
    DECLARE @dia_chi NVARCHAR(50);
    DECLARE @sodt NVARCHAR(15);
    DECLARE @tong_chi_tieu FLOAT;
    DECLARE @rank NVARCHAR(200);

    -- Tạo bảng tạm để lưu kết quả
    DECLARE @ResultTable TABLE (
        MaKhach CHAR(15),
        TenKhach NVARCHAR(50),
        DiaChi NVARCHAR(50),
        SoDT NVARCHAR(15),
        TongChiTieu FLOAT,
        Rank NVARCHAR(200)
    );
END;

    -- Khởi tạo con trỏ để lấy thông tin khách hàng
    DECLARE khach_hang_cursor CURSOR FOR
    SELECT MAKH, TENKH, DIACHI, SODT FROM KHACHHANG;

    OPEN khach_hang_cursor;

	FETCH NEXT FROM khach_hang_cursor INTO @ma_khach, @ten_khach, @dia_chi, @sodt;

    WHILE @@FETCH_STATUS = 0
    BEGIN
        -- Gọi thủ tục để tính toán tổng chi tiêu và hạng của khách hàng
        EXEC P_GETLOAIKH @ma_khach, @tong_chi_tieu OUTPUT, @rank OUTPUT;

        -- Thêm kết quả vào bảng tạm
        INSERT INTO @ResultTable (MaKhach, TenKhach, DiaChi, SoDT, TongChiTieu, Rank)
        VALUES (@ma_khach, @ten_khach, @dia_chi, @sodt, @tong_chi_tieu, @rank);

        FETCH NEXT FROM khach_hang_cursor INTO @ma_khach, @ten_khach, @dia_chi, @sodt;

    CLOSE khach_hang_cursor;
    DEALLOCATE khach_hang_cursor;

    -- Xuất toàn bộ dữ liệu từ bảng tạm
    SELECT * FROM @ResultTable;
END;

select * from NHANVIEN
select * from THONGTINNHANVIEN
--------
CREATE PROC P_GET_COLUMN_NAME @TABLE_NAME NVARCHAR(MAX)
AS
BEGIN
	SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = @TABLE_NAME
END

EXEC P_GET_COLUMN_NAME 'KHACHHANG'

CREATE PROC [dbo].[TIMKIEM_HANGHOA_KHOANGGIA](@GIADAU FLOAT, @GIACUOI FLOAT)
AS
	BEGIN
		SELECT * 
		FROM HANGHOA
		WHERE DONGIA BETWEEN @GIADAU AND @GIACUOI
	END
CREATE PROC [dbo].[TIMKIEM_HANGHOA_TEN](@TENSP NVARCHAR(100))
AS
	BEGIN
		SELECT * 
		FROM HANGHOA
		WHERE TENHANG LIKE N'%'+@TENSP+'%'
	END
CREATE PROC [dbo].[TIMKIEM_HANGHOA_TEN_KHOANGGIA](@TENSP NVARCHAR(100), @GIADAU FLOAT, @GIACUOI FLOAT)
AS
	BEGIN
		SELECT * 
		FROM HANGHOA
		WHERE TENHANG LIKE N'%'+@TENSP+'%'
		AND DONGIA BETWEEN @GIADAU AND @GIACUOI
	END